const fs = require('fs');
const path = require('path');

// Bundle analyzer setup
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
})

// Custom redirects - Add your manual redirects here
const customRedirects = [
  // Example:
  // { source: '/old-url', destination: '/new-url', permanent: true },
  // { source: '/old-post-title-lyrics', destination: '/new-post-title-lyrics.html', permanent: true },
  { source: '/raavana-mavan-da-lyrics-in-tamil-jana-nayagan.html', destination: '/ravana-mavan-da-lyrics-in-tamil-jana-nayagan.html', permanent: true },
  { source: '/thenpandi-tamile-en-singara-kuyile-lyrics.html', destination: '/thenpandi-tamile-en-singara-kuyile-song.html', permanent: true },
{ source: '/oru-thadavai-solvaya-lyrics-vaseegara.html', destination: '/oru-thadavai-solvaya-lyrics-vaseegara_31.html', permanent: true },
{ source: '/aathichudi-lyrics-tn-07-al-4777-song_14.html', destination: '/aathichudi-lyrics-tn-07-al-4777-song.html', permanent: true },
{ source: '/aathichuudi-full-song-lyrics-part-1_35.html', destination: '/aathichuudi-full-song-lyrics-part-1.html', permanent: true },
{ source: '/aathichudi-mini-lyrics-tn-07-4777-song_13.html', destination: '/aathichudi-mini-lyrics-tn-07-4777-song.html', permanent: true },
{ source: '/kallil-aadum-lyrics-anandha-thaandavam_6.html', destination: '/kallil-aadum-lyrics-anandha-thaandavam.html', permanent: true },
{ source: '/siva-manasula-sakthi-song-lyrics_12.html', destination: '/siva-manasula-sakthi-song-lyrics.html', permanent: true },
{ source: '/ayan-songs-lyrics_21.html', destination: '/ayan-songs-lyrics.html', permanent: true },
{ source: '/oyaayiye-yaayiye-lyrics-ayan-song-lyrics_21.html', destination: '/oyaayiye-yaayiye-lyrics-ayan-song-lyrics.html', permanent: true },
{ source: '/maalai-neram-lyrics-aayiraththil-oruvan_77.html', destination: '/maalai-neram-lyrics-aayiraththil-oruvan.html', permanent: true },
{ source: '/masilamani-song-lyrics_4.html', destination: '/masilamani-song-lyrics.html', permanent: true },
{ source: '/kanthasamy-full-song-lyrics_61.html', destination: '/kanthasamy-full-song-lyrics.html', permanent: true },
{ source: '/kanthasamy-song-lyrics_18.html', destination: '/kanthasamy-song-lyrics.html', permanent: true },
{ source: '/excuse-me-mr-kanthasamy-song-lyrics_70.html', destination: '/excuse-me-mr-kanthasamy-song-lyrics.html', permanent: true },
{ source: '/kanthasamy-en-peru-meenakumari-lyrics_56.html', destination: '/kanthasamy-en-peru-meenakumari-lyrics.html', permanent: true },
{ source: '/oru-punnagai-thane-lyrics-theeratha_85.html', destination: '/oru-punnagai-thane-lyrics-theeratha.html', permanent: true },
{ source: '/vaama-duraiyamma-song-lyrics_9.html', destination: '/vaama-duraiyamma-song-lyrics.html', permanent: true },
{ source: '/un-perai-sollum-pothe-lyrics-angadi_2.html', destination: '/un-perai-sollum-pothe-lyrics-angadi.html', permanent: true },
{ source: '/mudhal-pen-niyae-lyrics-thambikku-indha_95.html', destination: '/mudhal-pen-niyae-lyrics-thambikku-indha.html', permanent: true },
{ source: '/hosanna-lyrics-vinnaithaandi-varuvaaaya_63.html', destination: '/hosanna-lyrics-vinnaithaandi-varuvaaaya.html', permanent: true },
{ source: '/mannipaaya-lyrics-vinnaithaandi_6.html', destination: '/mannipaaya-lyrics-vinnaithaandi.html', permanent: true },
{ source: '/kannukul-kannai-lyrics-vinnaithaandi_75.html', destination: '/kannukul-kannai-lyrics-vinnaithaandi.html', permanent: true },
{ source: '/anbil-avan-lyrics-vinnaithaadi-varuvaya_25.html', destination: '/anbil-avan-lyrics-vinnaithaadi-varuvaya.html', permanent: true },
{ source: '/vinnaithaandi-varuvaayaa-song-lyrics_17.html', destination: '/vinnaithaandi-varuvaayaa-song-lyrics.html', permanent: true },
{ source: '/vazhkai-oru-lyrics-inidhu-inidhu-lyrics_44.html', destination: '/vazhkai-oru-lyrics-inidhu-inidhu-lyrics.html', permanent: true },
{ source: '/anbulla-sandhya-lyrics-kadhal-solla_61.html', destination: '/anbulla-sandhya-lyrics-kadhal-solla.html', permanent: true },
{ source: '/oh-shala-shala-lyrics-kaadhal-solla_80.html', destination: '/oh-shala-shala-lyrics-kaadhal-solla.html', permanent: true },
{ source: '/irumbile-oru-idhaiyam-lyrics-endhiran_3.html', destination: '/irumbile-oru-idhaiyam-lyrics-endhiran.html', permanent: true },
{ source: '/nan-mahaan-alla-song-lyrics_41.html', destination: '/nan-mahaan-alla-song-lyrics.html', permanent: true },
{ source: '/gore-gore-gogore-lyrics-moscowin-kaveri_89.html', destination: '/gore-gore-gogore-lyrics-moscowin-kaveri.html', permanent: true },
{ source: '/oru-vaanavillin-pakkathilae-lyrics_13.html', destination: '/oru-vaanavillin-pakkathilae-lyrics.html', permanent: true },
{ source: '/oru-paithiyam-pidikuthu-lyrics-baana_14.html', destination: '/oru-paithiyam-pidikuthu-lyrics-baana.html', permanent: true },
{ source: '/thaakkuthe-kan-thaakkuthe-lyrics-baana_90.html', destination: '/thaakkuthe-kan-thaakkuthe-lyrics-baana.html', permanent: true },
{ source: '/thee-illai-pugai-illai-lyrics-engeyum_64.html', destination: '/thee-illai-pugai-illai-lyrics-engeyum.html', permanent: true },
{ source: '/engeyum-kadhal-lyrics-engeyum-kadhal_60.html', destination: '/engeyum-kadhal-lyrics-engeyum-kadhal.html', permanent: true },
{ source: '/nenjil-nenjil-idho-song-lyrics-engeyum_19.html', destination: '/nenjil-nenjil-idho-song-lyrics-engeyum.html', permanent: true },
{ source: '/engeyum-kadhal-song-track-list-lyrics_5.html', destination: '/engeyum-kadhal-song-track-list-lyrics.html', permanent: true },
{ source: '/thenmerku-paruvakaatru-song-lyrics_12.html', destination: '/thenmerku-paruvakaatru-song-lyrics.html', permanent: true },
{ source: '/ussumu-laresay-sedhiki-edutha-lyrics_8.html', destination: '/ussumu-laresay-sedhiki-edutha-lyrics.html', permanent: true },
{ source: '/thiki-thiki-vandhu-lyrics-nagaram-song_1.html', destination: '/thiki-thiki-vandhu-lyrics-nagaram-song.html', permanent: true },
{ source: '/thediyae-thediyae-lyrics-va-quarter_3.html', destination: '/thediyae-thediyae-lyrics-va-quarter.html', permanent: true },
{ source: '/unnai-kan-thedhudhe-lyrics-va-quarter_3.html', destination: '/unnai-kan-thedhudhe-lyrics-va-quarter.html', permanent: true },
{ source: '/yaar-intha-penthan-lyrics-boss-engira_1.html', destination: '/yaar-intha-penthan-lyrics-boss-engira.html', permanent: true },
{ source: '/thathi-thaavum-paper-naan-lyrics-boss_91.html', destination: '/thathi-thaavum-paper-naan-lyrics-boss.html', permanent: true },
{ source: '/paarvai-undhan-lyrics-nil-gavani_32.html', destination: '/paarvai-undhan-lyrics-nil-gavani.html', permanent: true },
{ source: '/radhiye-radhiye-lyrics-aayiram-vilakku_21.html', destination: '/radhiye-radhiye-lyrics-aayiram-vilakku.html', permanent: true },
{ source: '/naan-romba-romba-lyrics-siruthai-songs_3.html', destination: '/naan-romba-romba-lyrics-siruthai-songs.html', permanent: true },
{ source: '/ada-da-en-meethu-lyrics-pathinaaru_59.html', destination: '/ada-da-en-meethu-lyrics-pathinaaru.html', permanent: true },
{ source: '/kaattu-chedikku-lyrics-pathinaaru-songs_22.html', destination: '/kaattu-chedikku-lyrics-pathinaaru-songs.html', permanent: true },
{ source: '/yaar-solli-kadhal-lyrics-pathinaaru_21.html', destination: '/yaar-solli-kadhal-lyrics-pathinaaru.html', permanent: true },
{ source: '/siruthai-songs-track-list-and-lyrics_47.html', destination: '/siruthai-songs-track-list-and-lyrics.html', permanent: true },
{ source: '/enge-en-idhayam-unnai-kandaene-lyrics_44.html', destination: '/enge-en-idhayam-unnai-kandaene-lyrics.html', permanent: true },
{ source: '/poove-poove-lyrics-singam-puli-songs_98.html', destination: '/poove-poove-lyrics-singam-puli-songs.html', permanent: true },
{ source: '/sada-sada-lyrics-kavalan-song-lyrics_27.html', destination: '/sada-sada-lyrics-kavalan-song-lyrics.html', permanent: true },
{ source: '/step-step-step-it-up-lyrics-kavalan_8.html', destination: '/step-step-step-it-up-lyrics-kavalan.html', permanent: true },
{ source: '/vaanam-song-track-list-lyrics_76.html', destination: '/vaanam-song-track-list-lyrics.html', permanent: true },
{ source: '/evan-di-una-pethan-lyrics-vaanam-songs_54.html', destination: '/evan-di-una-pethan-lyrics-vaanam-songs.html', permanent: true },
{ source: '/dhagudu-dhattham-lyrics-manmadhan-ambu_27.html', destination: '/dhagudu-dhattham-lyrics-manmadhan-ambu.html', permanent: true },
{ source: '/who-hero-lyrics-manmadhan-ambu-songs_23.html', destination: '/who-hero-lyrics-manmadhan-ambu-songs.html', permanent: true },
{ source: '/kavalan-or-kaavalan-songs-lyrics_56.html', destination: '/kavalan-or-kaavalan-songs-lyrics.html', permanent: true },
{ source: '/manmadhan-ambu-songs-lyrics_35.html', destination: '/manmadhan-ambu-songs-lyrics.html', permanent: true },
{ source: '/yathe-yathe-lyrics-aadukalam-songs_72.html', destination: '/yathe-yathe-lyrics-aadukalam-songs.html', permanent: true },
{ source: '/nangaai-o-mama-mama-lyrics-engeyum_58.html', destination: '/nangaai-o-mama-mama-lyrics-engeyum.html', permanent: true },
{ source: '/oru-malai-pozhuthil-lyrics-theneer_49.html', destination: '/oru-malai-pozhuthil-lyrics-theneer.html', permanent: true },
{ source: '/mellanna-siripalo-lyrics-theneer_17.html', destination: '/mellanna-siripalo-lyrics-theneer.html', permanent: true },
{ source: '/chinnanchiru-idhayathil-lyrics-narthagi_5.html', destination: '/chinnanchiru-idhayathil-lyrics-narthagi.html', permanent: true },
{ source: '/kettimelam-kottum-satham-lyrics-pesu_34.html', destination: '/kettimelam-kottum-satham-lyrics-pesu.html', permanent: true },
{ source: '/munpani-kaala-poovile-lyrics-seedan_6.html', destination: '/munpani-kaala-poovile-lyrics-seedan.html', permanent: true },
{ source: '/vennira-iravugal-song-lyrics-pesu-song_2.html', destination: '/vennira-iravugal-song-lyrics-pesu-song.html', permanent: true },
{ source: '/mazhai-varum-arikuri-lyrics-veppam-song_88.html', destination: '/mazhai-varum-arikuri-lyrics-veppam-song.html', permanent: true },
{ source: '/ennamo-yeadho-edho-lyrics-ko-song-lyrics_21.html', destination: '/ennamo-yeadho-edho-lyrics-ko-song-lyrics.html', permanent: true },
{ source: '/aga-naga-naga-lyrics-ko-songs-lyrics_33.html', destination: '/aga-naga-naga-lyrics-ko-songs-lyrics.html', permanent: true },
{ source: '/ulgamellam-unathallava-lyrics-i-will-be_56.html', destination: '/ulgamellam-unathallava-lyrics-i-will-be.html', permanent: true },
{ source: '/ko-song-lyrics_8.html', destination: '/ko-song-lyrics.html', permanent: true },
{ source: '/otha-sollaala-lyrics-aadukalam-songs_4.html', destination: '/otha-sollaala-lyrics-aadukalam-songs.html', permanent: true },
{ source: '/deiva-thirumagal-song-lyrics_9.html', destination: '/deiva-thirumagal-song-lyrics.html', permanent: true },
{ source: '/my-name-is-raju-baby-lyrics-maharaja_7.html', destination: '/my-name-is-raju-baby-lyrics-maharaja.html', permanent: true },
{ source: '/mexi-mexican-lady-lyrics-maharaja_6.html', destination: '/mexi-mexican-lady-lyrics-maharaja.html', permanent: true },
{ source: '/yededho-yededho-lyrics-sattapadi-kutram_79.html', destination: '/yededho-yededho-lyrics-sattapadi-kutram.html', permanent: true },
{ source: '/vaanam-lyrics-vaanam-song-lyrics_27.html', destination: '/vaanam-lyrics-vaanam-song-lyrics.html', permanent: true },
{ source: '/mazhaiyudhir-kaalam-lyrics-eththan-song_33.html', destination: '/mazhaiyudhir-kaalam-lyrics-eththan-song.html', permanent: true },
{ source: '/ennakaaga-unnakaaga-lyrics-kadhal-2_73.html', destination: '/ennakaaga-unnakaaga-lyrics-kadhal-2.html', permanent: true },
{ source: '/naa-vetta-pora-aadu-lyrics-kadhal-2_56.html', destination: '/naa-vetta-pora-aadu-lyrics-kadhal-2.html', permanent: true },
{ source: '/poovakkelu-lyrics-azhagarsamiyin_33.html', destination: '/poovakkelu-lyrics-azhagarsamiyin.html', permanent: true },
{ source: '/kullanari-koottam-song-lyrics_88.html', destination: '/kullanari-koottam-song-lyrics.html', permanent: true },
{ source: '/vizhigalile-vizhigalile-lyrics_27.html', destination: '/vizhigalile-vizhigalile-lyrics.html', permanent: true },
{ source: '/kadhal-enbadhai-lyrics-kullanari_42.html', destination: '/kadhal-enbadhai-lyrics-kullanari.html', permanent: true },
{ source: '/ready-readya-lyrics-mappillai-song_57.html', destination: '/ready-readya-lyrics-mappillai-song.html', permanent: true },
{ source: '/love-love-love-udi-lyrics-mappillai_55.html', destination: '/love-love-love-udi-lyrics-mappillai.html', permanent: true },
{ source: '/ennoda-rasi-nalla-raasi-lyrics_91.html', destination: '/ennoda-rasi-nalla-raasi-lyrics.html', permanent: true },
{ source: '/dhanush-in-mappillai-song-lyrics_81.html', destination: '/dhanush-in-mappillai-song-lyrics.html', permanent: true },
{ source: '/rowthiram-songs-lyrics_26.html', destination: '/rowthiram-songs-lyrics.html', permanent: true },
{ source: '/nadhiyile-song-lyrics-doo-songs-lyrics_23.html', destination: '/nadhiyile-song-lyrics-doo-songs-lyrics.html', permanent: true },
{ source: '/usura-thirudi-lyrics-konjam-veyil_69.html', destination: '/usura-thirudi-lyrics-konjam-veyil.html', permanent: true },
{ source: '/vela-vela-velayutham-fuil-lyrics_38.html', destination: '/vela-vela-velayutham-fuil-lyrics.html', permanent: true },
{ source: '/orey-oru-varthaikaga-lyrics-venghai_5.html', destination: '/orey-oru-varthaikaga-lyrics-venghai.html', permanent: true },
{ source: '/enna-solla-pora-lyrics-venghai-song_2.html', destination: '/enna-solla-pora-lyrics-venghai-song.html', permanent: true },
{ source: '/kaalangathale-lyrics-venghai-song-lyrics_11.html', destination: '/kaalangathale-lyrics-venghai-song-lyrics.html', permanent: true },
{ source: '/venghai-song-lyrics_55.html', destination: '/venghai-song-lyrics.html', permanent: true },
{ source: '/puraavai-vandhu-pogiraai-lyrics_67.html', destination: '/puraavai-vandhu-pogiraai-lyrics.html', permanent: true },
{ source: '/ninaivugal-thane-lyrics-kandaen-song_60.html', destination: '/ninaivugal-thane-lyrics-kandaen-song.html', permanent: true },
{ source: '/ithanai-yugamai-lyrics-udhayan-song_73.html', destination: '/ithanai-yugamai-lyrics-udhayan-song.html', permanent: true },
{ source: '/mansurukiathe-lyrics-karungaali-song_86.html', destination: '/mansurukiathe-lyrics-karungaali-song.html', permanent: true },
{ source: '/vilayadu-mankatha-lyrics-mankatha_67.html', destination: '/vilayadu-mankatha-lyrics-mankatha.html', permanent: true },
{ source: '/en-usuru-ennai-vittu-lyrics-sengathu_40.html', destination: '/en-usuru-ennai-vittu-lyrics-sengathu.html', permanent: true },
{ source: '/venpaniye-munpaniye-lyrics-ko-song_45.html', destination: '/venpaniye-munpaniye-lyrics-ko-song.html', permanent: true },
{ source: '/amali-thumali-lyrics-ko-song-lyrics_42.html', destination: '/amali-thumali-lyrics-ko-song-lyrics.html', permanent: true },
{ source: '/oru-malayoram-lyrics-avan-ivan-song_9.html', destination: '/oru-malayoram-lyrics-avan-ivan-song.html', permanent: true },
{ source: '/rasathi-pola-lyrics-avan-ivan-song_7.html', destination: '/rasathi-pola-lyrics-avan-ivan-song.html', permanent: true },
{ source: '/thirandhen-thirandhen-lyrics-vandhaan_80.html', destination: '/thirandhen-thirandhen-lyrics-vandhaan.html', permanent: true },
{ source: '/kanchana-mala-lyrics-vandhaan-vendraan_79.html', destination: '/kanchana-mala-lyrics-vandhaan-vendraan.html', permanent: true },
{ source: '/nagarudhe-nagarudhe-lyrics-vandhaan_50.html', destination: '/nagarudhe-nagarudhe-lyrics-vandhaan.html', permanent: true },
{ source: '/anjana-anjana-lyrics-vandhaan-vendraan_70.html', destination: '/anjana-anjana-lyrics-vandhaan-vendraan.html', permanent: true },
{ source: '/senganthal-kaiyaale-lyrics-rowthiram_0.html', destination: '/senganthal-kaiyaale-lyrics-rowthiram.html', permanent: true },
{ source: '/golimaare-gangsteru-lyrics-rowthiram_9.html', destination: '/golimaare-gangsteru-lyrics-rowthiram.html', permanent: true },
{ source: '/maalai-mangum-neram-lyrics-rowthiram_57.html', destination: '/maalai-mangum-neram-lyrics-rowthiram.html', permanent: true },
{ source: '/katha-solla-poren-lyrics-deiva_18.html', destination: '/katha-solla-poren-lyrics-deiva.html', permanent: true },
{ source: '/vizhigalil-oru-vaanavil-lyrics_54.html', destination: '/vizhigalil-oru-vaanavil-lyrics.html', permanent: true },
{ source: '/nee-korinaal-lyrics-180-song-lyrics_92.html', destination: '/nee-korinaal-lyrics-180-song-lyrics.html', permanent: true },
{ source: '/ethotho-ethotho-lyrics-ra-ra-song-lyrics_12.html', destination: '/ethotho-ethotho-lyrics-ra-ra-song-lyrics.html', permanent: true },
{ source: '/yetho-yethotho-lyrics-maruthavelu-song_37.html', destination: '/yetho-yethotho-lyrics-maruthavelu-song.html', permanent: true },
{ source: '/vaagai-sooda-va-song-lyrics_5.html', destination: '/vaagai-sooda-va-song-lyrics.html', permanent: true },
{ source: '/poraney-poraney-lyrics-vaagai-sooda-va_5.html', destination: '/poraney-poraney-lyrics-vaagai-sooda-va.html', permanent: true },
{ source: '/yuvan-yuvathi-song-lyrics_3.html', destination: '/yuvan-yuvathi-song-lyrics.html', permanent: true },
{ source: '/24-hours-lyrics-yuvan-yuvathi-song_3.html', destination: '/24-hours-lyrics-yuvan-yuvathi-song.html', permanent: true },
{ source: '/sara-sara-saara-lyrics-vaagai-sooda-va_2.html', destination: '/sara-sara-saara-lyrics-vaagai-sooda-va.html', permanent: true },
{ source: '/un-kannai-partha-piragu-lyrics-yuvan_2.html', destination: '/un-kannai-partha-piragu-lyrics-yuvan.html', permanent: true },
{ source: '/kalvaney-yen-kalvaney-lyrics-ninaivil_59.html', destination: '/kalvaney-yen-kalvaney-lyrics-ninaivil.html', permanent: true },
{ source: '/vandhaan-vendraan-songs-lyrics_8.html', destination: '/vandhaan-vendraan-songs-lyrics.html', permanent: true },
{ source: '/engeyum-eppodhum-song-lyrics_11.html', destination: '/engeyum-eppodhum-song-lyrics.html', permanent: true },
{ source: '/yuvan-movie-song-lyrics_47.html', destination: '/yuvan-movie-song-lyrics.html', permanent: true },
{ source: '/nilave-naanum-lyrics-yuvan-song-lyrics_9.html', destination: '/nilave-naanum-lyrics-yuvan-song-lyrics.html', permanent: true },
{ source: '/kan-paartha-neram-lyrics-yuvan-songs_47.html', destination: '/kan-paartha-neram-lyrics-yuvan-songs.html', permanent: true },
{ source: '/ennadaa-nadakuthu-inga-lyrics-kettavan_6.html', destination: '/ennadaa-nadakuthu-inga-lyrics-kettavan.html', permanent: true },
{ source: '/machi-open-bottle-lyrics-mankatha-song_13.html', destination: '/machi-open-bottle-lyrics-mankatha-song.html', permanent: true },
{ source: '/idhu-enga-balle-lakka-lyrics-mankatha_69.html', destination: '/idhu-enga-balle-lakka-lyrics-mankatha.html', permanent: true },
{ source: '/mankatha-song-lyrics_49.html', destination: '/mankatha-song-lyrics.html', permanent: true },
{ source: '/en-nanbane-lyrics-mankatha-songs-lyrics_47.html', destination: '/en-nanbane-lyrics-mankatha-songs-lyrics.html', permanent: true },
{ source: '/vaada-bin-laada-lyrics-mankatha-songs_58.html', destination: '/vaada-bin-laada-lyrics-mankatha-songs.html', permanent: true },
{ source: '/uyir-arundhadhey-lyrics-engeyum_7.html', destination: '/uyir-arundhadhey-lyrics-engeyum.html', permanent: true },
{ source: '/makkayala-makkayala-lyrics-naan-song_6.html', destination: '/makkayala-makkayala-lyrics-naan-song.html', permanent: true },
{ source: '/un-pere-theriyadhu-lyrics-engeyum_5.html', destination: '/un-pere-theriyadhu-lyrics-engeyum.html', permanent: true },
{ source: '/govinda-govinda-lyrics-engeyum-eppodhum_4.html', destination: '/govinda-govinda-lyrics-engeyum-eppodhum.html', permanent: true },
{ source: '/aiythaaney-lyrics-muthal-idam-song_59.html', destination: '/aiythaaney-lyrics-muthal-idam-song.html', permanent: true },
{ source: '/pappara-pappara-enga-ooru-lyrics-muthal_16.html', destination: '/pappara-pappara-enga-ooru-lyrics-muthal.html', permanent: true },
{ source: '/inga-vaanthey-lyrics-muthal-idam-song_56.html', destination: '/inga-vaanthey-lyrics-muthal-idam-song.html', permanent: true },
{ source: '/muthal-mudhal-idam-song-lyrics_44.html', destination: '/muthal-mudhal-idam-song-lyrics.html', permanent: true },
{ source: '/mayaka-oosi-lyrics-yuvan-yuvathi-song_9.html', destination: '/mayaka-oosi-lyrics-yuvan-yuvathi-song.html', permanent: true },
{ source: '/oh-ringa-ringa-song-lyrics-7am-arivu_74.html', destination: '/oh-ringa-ringa-song-lyrics-7am-arivu.html', permanent: true },
{ source: '/naan-bombay-ponnu-lyrics-vedi-song_8.html', destination: '/naan-bombay-ponnu-lyrics-vedi-song.html', permanent: true },
{ source: '/vedi-songs-lyrics_7.html', destination: '/vedi-songs-lyrics.html', permanent: true },
{ source: '/kadhalika-lyrics-vedi-song-lyrics_7.html', destination: '/kadhalika-lyrics-vedi-song-lyrics.html', permanent: true },
{ source: '/ippadi-mazhai-lyrics-vedi-song-lyrics_7.html', destination: '/ippadi-mazhai-lyrics-vedi-song-lyrics.html', permanent: true },
{ source: '/enna-aachu-lyrics-vedi-song-lyrics_7.html', destination: '/enna-aachu-lyrics-vedi-song-lyrics.html', permanent: true },
{ source: '/innum-enna-thozha-lyrics-7am-arivu-song_4.html', destination: '/innum-enna-thozha-lyrics-7am-arivu-song.html', permanent: true },
{ source: '/yamma-yamma-lyrics-7am-arivu-song-lyrics_4.html', destination: '/yamma-yamma-lyrics-7am-arivu-song-lyrics.html', permanent: true },
{ source: '/the-raise-of-damo-7am-arivu-song-lyrics_4.html', destination: '/7am-arivu-songs-lyrics.html', permanent: true },
{ source: '/velayutham-songs-track-list-lyrics_23.html', destination: '/velayutham-songs-track-list-lyrics.html', permanent: true },
{ source: '/sonna-puriyathu-lyrics-velayutham-song_30.html', destination: '/sonna-puriyathu-lyrics-velayutham-song.html', permanent: true },
{ source: '/idhuvarai-en-nenjai-lyrics-muran-song_93.html', destination: '/idhuvarai-en-nenjai-lyrics-muran-song.html', permanent: true },
{ source: '/andhimantharai-lyrics-muran-song-lyrics_0.html', destination: '/andhimantharai-lyrics-muran-song-lyrics.html', permanent: true },
{ source: '/cheran-muran-song-lyrics_74.html', destination: '/cheran-muran-song-lyrics.html', permanent: true },
{ source: '/molachu-moonu-lyrics-velayutham-song_44.html', destination: '/molachu-moonu-lyrics-velayutham-song.html', permanent: true },
{ source: '/chillax-lyrics-manjanathi-lyrics_81.html', destination: '/chillax-lyrics-manjanathi-lyrics.html', permanent: true },
{ source: '/maayam-seidhayo-lyrics-velayutham-song_11.html', destination: '/maayam-seidhayo-lyrics-velayutham-song.html', permanent: true },
{ source: '/velayutham-theme-song-lyrics-velayutham_76.html', destination: '/velayutham-theme-song-lyrics-velayutham.html', permanent: true },
{ source: '/rathathin-rathame-full-lyrics_54.html', destination: '/rathathin-rathame-full-lyrics.html', permanent: true },
{ source: '/osthi-maamey-lyrics-osthi-song-lyrics_24.html', destination: '/osthi-maamey-lyrics-osthi-song-lyrics.html', permanent: true },
{ source: '/kalasala-kalasala-song-lyrics-osthi_90.html', destination: '/kalasala-kalasala-song-lyrics-osthi.html', permanent: true },
{ source: '/osthi-songs-lyrics-track-list_99.html', destination: '/osthi-songs-lyrics-track-list.html', permanent: true },
{ source: '/en-uyir-ennai-vittu-lyrics-ra-one-song_36.html', destination: '/en-uyir-ennai-vittu-lyrics-ra-one-song.html', permanent: true },
{ source: '/senga-soola-kaara-lyrics-vaagai-sooda_5.html', destination: '/senga-soola-kaara-lyrics-vaagai-sooda.html', permanent: true },
{ source: '/chotta-chotta-ninaika-lyrics-engeyum_42.html', destination: '/chotta-chotta-ninaika-lyrics-engeyum.html', permanent: true },
{ source: '/pirai-thedum-lyrics-mayakkam-enna-song_73.html', destination: '/pirai-thedum-lyrics-mayakkam-enna-song.html', permanent: true },
{ source: '/rajapattai-single-song-lyrics-track-list_11.html', destination: '/rajapattai-single-song-lyrics-track-list.html', permanent: true },
{ source: '/nila-nila-poguthae-lyrics-aravaan-songs_6.html', destination: '/nila-nila-poguthae-lyrics-aravaan-songs.html', permanent: true },
{ source: '/naan-sonnadhum-lyrics-mayakkam-enna_31.html', destination: '/naan-sonnadhum-lyrics-mayakkam-enna.html', permanent: true },
{ source: '/mayakkam-enna-song-lyrics_22.html', destination: '/mayakkam-enna-song-lyrics.html', permanent: true },
{ source: '/oda-oda-oda-dhooram-lyrics-mayakkam_45.html', destination: '/oda-oda-oda-dhooram-lyrics-mayakkam.html', permanent: true },
{ source: '/kadhal-en-kadhal-lyrics-mayakkam-enna_4.html', destination: '/kadhal-en-kadhal-lyrics-mayakkam-enna.html', permanent: true },
{ source: '/7am-arivu-songs-lyrics_35.html', destination: '/7am-arivu-songs-lyrics.html', permanent: true },
{ source: '/kaattu-vazhi-pora-ponney-lyrics_4.html', destination: '/kaattu-vazhi-pora-ponney-lyrics.html', permanent: true },
{ source: '/mun-andhi-chaaral-lyrics-7am-arivu-song_93.html', destination: '/mun-andhi-chaaral-lyrics-7am-arivu-song.html', permanent: true },
{ source: '/yelle-lama-lyrics-7am-arivu-song-lyrics_53.html', destination: '/yelle-lama-lyrics-7am-arivu-song-lyrics.html', permanent: true },
{ source: '/oru-murai-oru-murai-lyrics-muppozhudhum_5.html', destination: '/oru-murai-oru-murai-lyrics-muppozhudhum.html', permanent: true },
{ source: '/mouna-guru-songs-lyrics_93.html', destination: '/mouna-guru-songs-lyrics.html', permanent: true },
{ source: '/anaamika-lyrics-mouna-guru-songs-lyrics_68.html', destination: '/anaamika-lyrics-mouna-guru-songs-lyrics.html', permanent: true },
{ source: '/yennaidhu-yenna-idhu-lyrics-mouna-guru_36.html', destination: '/yennaidhu-yenna-idhu-lyrics-mouna-guru.html', permanent: true },
{ source: '/vedi-pottu-lyrics-poraali-porali-song_47.html', destination: '/vedi-pottu-lyrics-poraali-porali-song.html', permanent: true },
{ source: '/why-this-kolaveri-di-lyrics-3-moondru_49.html', destination: '/why-this-kolaveri-di-lyrics-3-moondru.html', permanent: true },
{ source: '/neelavizhi-nilavai-lyrics-thulli_7.html', destination: '/neelavizhi-nilavai-lyrics-thulli.html', permanent: true },
{ source: '/muthal-murai-unnai-lyrics-thulli_7.html', destination: '/muthal-murai-unnai-lyrics-thulli.html', permanent: true },
{ source: '/kolaikaara-lyrics-thambi-vettothi_6.html', destination: '/kolaikaara-lyrics-thambi-vettothi.html', permanent: true },
{ source: '/poraali-porali-songs-lyrics_6.html', destination: '/poraali-porali-songs-lyrics.html', permanent: true },
{ source: '/ok-ok-songs-lyrics-track-list_2.html', destination: '/ok-ok-songs-lyrics-track-list.html', permanent: true },
{ source: '/rajapattai-songs-lyrics_26.html', destination: '/rajapattai-songs-lyrics.html', permanent: true },
{ source: '/podi-paiyyan-polave-lyrics-rajapattai_13.html', destination: '/podi-paiyyan-polave-lyrics-rajapattai.html', permanent: true },
{ source: '/muthada-chammak-challo-lyrics-ra-one_80.html', destination: '/muthada-chammak-challo-lyrics-ra-one.html', permanent: true },
{ source: '/thananana-thanthanaa-lyrics-vithagan_9.html', destination: '/thananana-thanthanaa-lyrics-vithagan.html', permanent: true },
{ source: '/vithagan-songs-lyrics_73.html', destination: '/vithagan-songs-lyrics.html', permanent: true },
{ source: '/neduvaali-lyrics-osthi-osthe-song-lyrics_23.html', destination: '/neduvaali-lyrics-osthi-osthe-song-lyrics.html', permanent: true },
{ source: '/ikkuthe-kangal-vikkuthe-lyrics-vithagan_31.html', destination: '/ikkuthe-kangal-vikkuthe-lyrics-vithagan.html', permanent: true },
{ source: '/kadalirandu-thuliyirandaai-lyrics_44.html', destination: '/kadalirandu-thuliyirandaai-lyrics.html', permanent: true },
{ source: '/unnale-unnale-lyrics-osthi-osthe-songs_69.html', destination: '/unnale-unnale-lyrics-osthi-osthe-songs.html', permanent: true },
{ source: '/pondatti-song-lyrics-osthi-song-lyrics_85.html', destination: '/pondatti-song-lyrics-osthi-song-lyrics.html', permanent: true },
{ source: '/heartiley-battery-all-is-well-lyrics_14.html', destination: '/heartiley-battery-all-is-well-lyrics.html', permanent: true },
{ source: '/en-nanban-frienda-pola-lyrics-nanban_79.html', destination: '/en-nanban-frienda-pola-lyrics-nanban.html', permanent: true },
{ source: '/muppozhudhum-un-karpanaigal-song-lyrics_35.html', destination: '/muppozhudhum-un-karpanaigal-song-lyrics.html', permanent: true },
{ source: '/sokkupodi-potaale-lyrics-muk-songs_18.html', destination: '/sokkupodi-potaale-lyrics-muk-songs.html', permanent: true },
{ source: '/yaar-aval-yaaro-lyrics-muk-songs-lyrics_35.html', destination: '/yaar-aval-yaaro-lyrics-muk-songs-lyrics.html', permanent: true },
{ source: '/mazhai-pozhiyum-lyrics-muk-songs-lyrics_1.html', destination: '/mazhai-pozhiyum-lyrics-muk-songs-lyrics.html', permanent: true },
{ source: '/why-this-kolaveri-di-lyrics-dhanush-3_31.html', destination: '/why-this-kolaveri-di-lyrics-dhanush-3.html', permanent: true },
{ source: '/kattipidi-lyrics-vettai-songs-lyrics_12.html', destination: '/kattipidi-lyrics-vettai-songs-lyrics.html', permanent: true },
{ source: '/pappapappa-lyrics-papparappa-lyrics_50.html', destination: '/pappapappa-lyrics-papparappa-lyrics.html', permanent: true },
{ source: '/rajapattai-songs-lyrics_40.html', destination: '/rajapattai-songs-lyrics.html', permanent: true },
{ source: '/paniye-pani-poove-lyrics-rajapattai_64.html', destination: '/paniye-pani-poove-lyrics-rajapattai.html', permanent: true },
{ source: '/laddu-laddu-lyrics-rajapattai-songs_81.html', destination: '/laddu-laddu-lyrics-rajapattai-songs.html', permanent: true },
{ source: '/vettai-songs-lyrics-track-list_26.html', destination: '/vettai-songs-lyrics-track-list.html', permanent: true },
{ source: '/aambalaikum-pombalaikum-lyrics-kazhugu_87.html', destination: '/aambalaikum-pombalaikum-lyrics-kazhugu.html', permanent: true },
{ source: '/mambattiyan-songs-lyrics_11.html', destination: '/mambattiyan-songs-lyrics.html', permanent: true },
{ source: '/yedho-aaghudae-lyrics-mambattiyan-songs_67.html', destination: '/yedho-aaghudae-lyrics-mambattiyan-songs.html', permanent: true },
{ source: '/kazhugu-songs-lyrics-yuvan_41.html', destination: '/kazhugu-songs-lyrics-yuvan.html', permanent: true },
{ source: '/aathadi-manasudhan-lyrics-kazhugu-songs_92.html', destination: '/aathadi-manasudhan-lyrics-kazhugu-songs.html', permanent: true },
{ source: '/paathagathi-kannupattu-lyrics-kazhugu_11.html', destination: '/paathagathi-kannupattu-lyrics-kazhugu.html', permanent: true },
{ source: '/po-nee-po-lyrics-3-songs-lyrics-in_14.html', destination: '/po-nee-po-lyrics-3-songs-lyrics-in.html', permanent: true },
{ source: '/nee-paartha-vizhigal-lyrics-3-songs_14.html', destination: '/nee-paartha-vizhigal-lyrics-3-songs.html', permanent: true },
{ source: '/asku-laska-lyrics-in-thanglish-english_14.html', destination: '/asku-laska-lyrics-in-thanglish-english.html', permanent: true },
{ source: '/en-frienda-pola-lyrics-in-thanglish-and_14.html', destination: '/en-frienda-pola-lyrics-in-thanglish-and.html', permanent: true },
{ source: '/so-all-we-need-is-love-anthem-for-world_90.html', destination: '/so-all-we-need-is-love-anthem-for-world.html', permanent: true },
{ source: '/kannazhaga-lyrics-3-songs-lyrics_24.html', destination: '/kannazhaga-lyrics-3-songs-lyrics.html', permanent: true },
{ source: '/common-girls-lyrics-3-songs-lyrics_33.html', destination: '/common-girls-lyrics-3-songs-lyrics.html', permanent: true },
{ source: '/nee-paartha-vizhigal-lyrics-3-songs_62.html', destination: '/nee-paartha-vizhigal-lyrics-3-songs.html', permanent: true },
{ source: '/idhazhin-oram-lyrics-3-songs-lyrics_38.html', destination: '/idhazhin-oram-lyrics-3-songs-lyrics.html', permanent: true },
{ source: '/po-nee-po-lyrics-3-songs-lyrics_91.html', destination: '/po-nee-po-lyrics-3-songs-lyrics.html', permanent: true },
{ source: '/3-moondru-moonu-songs-lyrics_4.html', destination: '/3-moondru-moonu-songs-lyrics.html', permanent: true },
{ source: '/asku-laska-tamil-lyrics-nanban-songs_28.html', destination: '/asku-laska-tamil-lyrics-nanban-songs.html', permanent: true },
{ source: '/nalla-nanban-lyrics-nanban-songs-lyrics_12.html', destination: '/nalla-nanban-lyrics-nanban-songs-lyrics.html', permanent: true },
{ source: '/irukaanna-iduppirukaana-ilaiyaana_90.html', destination: '/irukaanna-iduppirukaana-ilaiyaana.html', permanent: true },
{ source: '/nanban-songs-lyrics-track-list-lyrics_93.html', destination: '/nanban-songs-lyrics-track-list-lyrics.html', permanent: true },
{ source: '/asku-laska-lyrics-nanban-songs-lyrics_74.html', destination: '/asku-laska-lyrics-nanban-songs-lyrics.html', permanent: true },
{ source: '/endhan-kan-munne-lyrics-nanban-lyrics_75.html', destination: '/endhan-kan-munne-lyrics-nanban-lyrics.html', permanent: true },
{ source: '/venaam-macha-lyrics-oru-kal-oru-kannadi_70.html', destination: '/venaam-macha-lyrics-oru-kal-oru-kannadi.html', permanent: true },
{ source: '/adada-oru-lyrics-ok-ok-lyrics_1.html', destination: '/adada-oru-lyrics-ok-ok-lyrics.html', permanent: true },
{ source: '/kadhal-oru-butterfly-lyrics-ok-ok-lyrics_3.html', destination: '/kadhal-oru-butterfly-lyrics-ok-ok-lyrics.html', permanent: true },
{ source: '/ok-ok-songs-lyrics_3.html', destination: '/ok-ok-songs-lyrics.html', permanent: true },
{ source: '/kangal-neeye-lyrics-muk-songs-lyrics-in_45.html', destination: '/kangal-neeye-lyrics-muk-songs-lyrics-in.html', permanent: true },
{ source: '/mazhai-pozhiyum-lyrics-muk-in-thanglish_23.html', destination: '/mazhai-pozhiyum-lyrics-muk-in-thanglish.html', permanent: true },
{ source: '/en-uyire-unplugged-lyrics-maalai_10.html', destination: '/en-uyire-unplugged-lyrics-maalai.html', permanent: true },
{ source: '/en-uyire-lyrics-mpm-songs-lyrics-in_15.html', destination: '/en-uyire-lyrics-mpm-songs-lyrics-in.html', permanent: true },
{ source: '/oh-baby-girl-lyrics-maalai-pozhuthin_15.html', destination: '/oh-baby-girl-lyrics-maalai-pozhuthin.html', permanent: true },
{ source: '/vilayaattaa-padagotty-lyrics-dhoni_11.html', destination: '/vilayaattaa-padagotty-lyrics-dhoni.html', permanent: true },
{ source: '/vijay-thalapathy-anthem-thalaiva_4.html', destination: '/vijay-thalapathy-anthem-thalaiva.html', permanent: true },
{ source: '/sachin-anthem-lyrics-sachin-song-lyrics_21.html', destination: '/sachin-anthem-lyrics-sachin-song-lyrics.html', permanent: true },
{ source: '/un-kangal-kannaadi-lyrics-krishnaveni_38.html', destination: '/un-kangal-kannaadi-lyrics-krishnaveni.html', permanent: true },
{ source: '/dhoni-songs-lyrics_0.html', destination: '/dhoni-songs-lyrics.html', permanent: true },
{ source: '/oru-megham-lyrics-ishtam-songs-lyrics_27.html', destination: '/oru-megham-lyrics-ishtam-songs-lyrics.html', permanent: true },
{ source: '/mokka-manusha-lyrics-kalakalappu-songs_23.html', destination: '/mokka-manusha-lyrics-kalakalappu-songs.html', permanent: true },
{ source: '/kalakalappu-masala-cafe-songs-lyrics_23.html', destination: '/kalakalappu-masala-cafe-songs-lyrics.html', permanent: true },
{ source: '/angelina-lyrics-kalakalappu-song-lyrics_23.html', destination: '/angelina-lyrics-kalakalappu-song-lyrics.html', permanent: true },
{ source: '/ava-thirumbipaarthu-lyrics-kalakalappu_23.html', destination: '/ava-thirumbipaarthu-lyrics-kalakalappu.html', permanent: true },
{ source: '/ivalunga-imsai-thaanga-mudiyala-lyrics_23.html', destination: '/ivalunga-imsai-thaanga-mudiyala-lyrics.html', permanent: true },
{ source: '/maatraan-maatran-songs-lyrics-track-list_14.html', destination: '/maatraan-maatran-songs-lyrics-track-list.html', permanent: true },
{ source: '/venaam-macha-lyrics-in-tamil_14.html', destination: '/venaam-macha-lyrics-in-tamil.html', permanent: true },
{ source: '/azhage-azhage-lyrics-ok-ok-songs-lyrics_11.html', destination: '/azhage-azhage-lyrics-ok-ok-songs-lyrics.html', permanent: true },
{ source: '/kannazhaga-lyrics-in-tamil_9.html', destination: '/kannazhaga-lyrics-in-tamil.html', permanent: true },
{ source: '/po-ne-po-lyrics-in-tamil_9.html', destination: '/po-ne-po-lyrics-in-tamil.html', permanent: true },
{ source: '/va-macha-va-chennai-super-kings-csk_4.html', destination: '/va-macha-va-chennai-super-kings-csk.html', permanent: true },
{ source: '/sir-udanay-lyrics-business-man-song_28.html', destination: '/sir-udanay-lyrics-business-man-song.html', permanent: true },
{ source: '/venam-machan-lyrics-in-english_27.html', destination: '/venam-machan-lyrics-in-english.html', permanent: true },
{ source: '/manikanakkil-sirithu-lyrics-raja_5.html', destination: '/manikanakkil-sirithu-lyrics-raja.html', permanent: true },
{ source: '/vella-bambaram-lyrics-saguni-songs_4.html', destination: '/vella-bambaram-lyrics-saguni-songs.html', permanent: true },
{ source: '/asathum-azhagu-lyrics-raattinam-songs_20.html', destination: '/asathum-azhagu-lyrics-raattinam-songs.html', permanent: true },
{ source: '/ava-thirumbipaarthu-lyrics-in-tamil_19.html', destination: '/ava-thirumbipaarthu-lyrics-in-tamil.html', permanent: true },
{ source: '/kalangal-lyrics-in-tamil-thadaiyara_15.html', destination: '/kalangal-lyrics-in-tamil-thadaiyara.html', permanent: true },
{ source: '/naan-poondamalli-lyrics-thadaiyara_13.html', destination: '/naan-poondamalli-lyrics-thadaiyara.html', permanent: true },
{ source: '/kalangal-lyrics-thadaiyara-thakka-song_13.html', destination: '/kalangal-lyrics-thadaiyara-thakka-song.html', permanent: true },
{ source: '/thadaiyara-thaakka-songs-lyrics_9.html', destination: '/thadaiyara-thaakka-songs-lyrics.html', permanent: true },
{ source: '/kelamalae-paaykiraai-lyrics-in-tamil_9.html', destination: '/kelamalae-paaykiraai-lyrics-in-tamil.html', permanent: true },
{ source: '/kelamale-paaykiraai-lyrics-thadaiyara_9.html', destination: '/kelamale-paaykiraai-lyrics-thadaiyara.html', permanent: true },
{ source: '/billa-2-idhayam-lyrics-in-tamil_5.html', destination: '/billa-2-idhayam-lyrics-in-tamil.html', permanent: true },
{ source: '/unakkulle-mirugam-lyrics-billa-2-song_1.html', destination: '/unakkulle-mirugam-lyrics-billa-2-song.html', permanent: true },
{ source: '/yedho-mayakkam-lyrics-billa-2-songs_1.html', destination: '/yedho-mayakkam-lyrics-billa-2-songs.html', permanent: true },
{ source: '/idhayam-indha-idhayam-lyrics-billa-2_1.html', destination: '/idhayam-indha-idhayam-lyrics-billa-2.html', permanent: true },
{ source: '/gangster-lyrics-billa-2-songs-lyrics_28.html', destination: '/gangster-lyrics-billa-2-songs-lyrics.html', permanent: true },
{ source: '/madurai-ponnu-lyrics-billa-2-song-lyrics_28.html', destination: '/madurai-ponnu-lyrics-billa-2-song-lyrics.html', permanent: true },
{ source: '/billa-2-songs-lyrics_28.html', destination: '/billa-2-songs-lyrics.html', permanent: true },
{ source: '/naan-ee-songs-lyrics_27.html', destination: '/naan-ee-songs-lyrics.html', permanent: true },
{ source: '/veesum-velichathile-lyrics-naan-ee_25.html', destination: '/veesum-velichathile-lyrics-naan-ee.html', permanent: true },
{ source: '/konjam-konjam-lyrics-in-english_24.html', destination: '/konjam-konjam-lyrics-in-english.html', permanent: true },
{ source: '/vaaya-moodi-summa-iru-da-lyrics-in-tamil_21.html', destination: '/vaaya-moodi-summa-iru-da-lyrics-in-tamil.html', permanent: true },
{ source: '/vaaya-moodi-summa-iru-da-lyrics_21.html', destination: '/vaaya-moodi-summa-iru-da-lyrics.html', permanent: true },
{ source: '/mugamoodi-songs-lyrics_21.html', destination: '/mugamoodi-songs-lyrics.html', permanent: true },
{ source: '/maayavi-lyrics-in-tamil-mugamoodi-songs_21.html', destination: '/maayavi-lyrics-in-tamil-mugamoodi-songs.html', permanent: true },
{ source: '/nkpm-naduvula-konjam-pakkatha-kanom_21.html', destination: '/nkpm-naduvula-konjam-pakkatha-kanom.html', permanent: true },
{ source: '/o-crazy-minnal-lyrics-naduvula-konjam_21.html', destination: '/o-crazy-minnal-lyrics-naduvula-konjam.html', permanent: true },
{ source: '/omelette-potta-lyrics-naduvula-konjam_21.html', destination: '/omelette-potta-lyrics-naduvula-konjam.html', permanent: true },
{ source: '/rettai-kadire-lyrics-maattrraan-songs_14.html', destination: '/rettai-kadire-lyrics-maattrraan-songs.html', permanent: true },
{ source: '/saguni-songs-lyrics_4.html', destination: '/saguni-songs-lyrics.html', permanent: true },
{ source: '/manasellam-mazhaiye-lyrics-saguni-songs_4.html', destination: '/manasellam-mazhaiye-lyrics-saguni-songs.html', permanent: true },
{ source: '/yaaro-yaaro-lyrics-in-tamil-maattrraan_10.html', destination: '/yaaro-yaaro-lyrics-in-tamil-maattrraan.html', permanent: true },
{ source: '/nani-koni-rani-lyrics-in-tamil_10.html', destination: '/nani-koni-rani-lyrics-in-tamil.html', permanent: true },
{ source: '/kaal-mulaitha-poove-lyrics-in-tamil_9.html', destination: '/kaal-mulaitha-poove-lyrics-in-tamil.html', permanent: true },
{ source: '/yaaro-yaaro-naan-yaaro-lyrics_9.html', destination: '/yaaro-yaaro-naan-yaaro-lyrics.html', permanent: true },
{ source: '/kaal-mulaitha-poove-lyrics-maattrraan_9.html', destination: '/kaal-mulaitha-poove-lyrics-maattrraan.html', permanent: true },
{ source: '/theeye-theeye-lyrics-maattrraan-song_8.html', destination: '/theeye-theeye-lyrics-maattrraan-song.html', permanent: true },
{ source: '/ulaginil-miga-uyaram-lyrics-naan-songs_4.html', destination: '/ulaginil-miga-uyaram-lyrics-naan-songs.html', permanent: true },
{ source: '/thappellam-thappae-illai-lyrics-naan_4.html', destination: '/thappellam-thappae-illai-lyrics-naan.html', permanent: true },
{ source: '/naan-songs-lyrics_4.html', destination: '/naan-songs-lyrics.html', permanent: true },
{ source: '/nani-koni-rani-koiyum-kangal-lyrics_3.html', destination: '/nani-koni-rani-koiyum-kangal-lyrics.html', permanent: true },
{ source: '/siva-thaandavam-thaandavam-theme-songs_2.html', destination: '/siva-thaandavam-thaandavam-theme-songs.html', permanent: true },
{ source: '/soi-soi-soi-soi-lyrics-kumki-songs_30.html', destination: '/soi-soi-soi-soi-lyrics-kumki-songs.html', permanent: true },
{ source: '/ayayayayo-aananthamey-lyrics-kumki-song_30.html', destination: '/ayayayayo-aananthamey-lyrics-kumki-song.html', permanent: true },
{ source: '/hey-crazy-penne-lyrics-naduvula-konjam_29.html', destination: '/hey-crazy-penne-lyrics-naduvula-konjam.html', permanent: true },
{ source: '/sollitaley-ava-kaadhala-lyrics-kumki_28.html', destination: '/sollitaley-ava-kaadhala-lyrics-kumki.html', permanent: true },
{ source: '/kumki-songs-lyrics_28.html', destination: '/kumki-songs-lyrics.html', permanent: true },
{ source: '/makkayala-makkayala-lyrics-in-tamil_29.html', destination: '/makkayala-makkayala-lyrics-in-tamil.html', permanent: true },
{ source: '/onnum-puriyala-lyrics-kumki-songs-lyrics_28.html', destination: '/onnum-puriyala-lyrics-kumki-songs-lyrics.html', permanent: true },
{ source: '/yella-oorum-lyrics-kumki-songs-lyrics_28.html', destination: '/yella-oorum-lyrics-kumki-songs-lyrics.html', permanent: true },
{ source: '/nee-yeppo-pulla-lyrics-kumki-songs_28.html', destination: '/nee-yeppo-pulla-lyrics-kumki-songs.html', permanent: true },
{ source: '/ayayayoo-aananthamey-lyrics-kumki-songs_28.html', destination: '/ayayayoo-aananthamey-lyrics-kumki-songs.html', permanent: true },
{ source: '/ayayayyo-aananthame-lyrics-in-tamil_28.html', destination: '/ayayayyo-aananthame-lyrics-in-tamil.html', permanent: true },
{ source: '/soi-soi-lyrics-in-tamil_28.html', destination: '/soi-soi-lyrics-in-tamil.html', permanent: true },
{ source: '/aadi-pona-aavani-lyrics-in-tamil_26.html', destination: '/aadi-pona-aavani-lyrics-in-tamil.html', permanent: true },
{ source: '/aadi-ponaa-aavani-lyrics-atta-kathi_26.html', destination: '/aadi-ponaa-aavani-lyrics-atta-kathi.html', permanent: true },
{ source: '/will-you-be-there-lyrics-thaandavam_17.html', destination: '/will-you-be-there-lyrics-thaandavam.html', permanent: true },
{ source: '/oru-paadhi-kadhavu-lyrics-thaandavam_17.html', destination: '/oru-paadhi-kadhavu-lyrics-thaandavam.html', permanent: true },
{ source: '/adhigaalai-pookal-lyrics-thandavam_17.html', destination: '/adhigaalai-pookal-lyrics-thandavam.html', permanent: true },
{ source: '/anicham-poovazhagi-lyrics-thandavam_17.html', destination: '/anicham-poovazhagi-lyrics-thandavam.html', permanent: true },
{ source: '/uyirin-uyire-lyrics-thandavam-songs_17.html', destination: '/uyirin-uyire-lyrics-thandavam-songs.html', permanent: true },
{ source: '/thandavam-thaandavam-songs-lyrics_17.html', destination: '/thandavam-thaandavam-songs-lyrics.html', permanent: true },
{ source: '/yaaradi-yaaradi-mohini-lyrics_17.html', destination: '/yaaradi-yaaradi-mohini-lyrics.html', permanent: true },
{ source: '/theeye-theeye-lyrics-in-tamil_10.html', destination: '/theeye-theeye-lyrics-in-tamil.html', permanent: true },
{ source: '/thuppakki-songs-lyrics-track-list_30.html', destination: '/thuppakki-songs-lyrics-track-list.html', permanent: true },
{ source: '/aadhi-bhagavan-songs-lyrics-tracklist_14.html', destination: '/aadhi-bhagavan-songs-lyrics-tracklist.html', permanent: true },
{ source: '/love-panlama-venama-lyrics-poda-podi_6.html', destination: '/love-panlama-venama-lyrics-poda-podi.html', permanent: true },
{ source: '/chennai-anthem-by-simbu-vanthaarai_4.html', destination: '/chennai-anthem-by-simbu-vanthaarai.html', permanent: true },
{ source: '/sattru-munbu-paartha-lyrics-in-tamil-nep_3.html', destination: '/sattru-munbu-paartha-lyrics-in-tamil-nep.html', permanent: true },
{ source: '/mudhal-murai-lyrics-in-tamil-nep_3.html', destination: '/mudhal-murai-lyrics-in-tamil-nep.html', permanent: true },
{ source: '/ennodu-vaa-vaa-endru-lyrics-in-tamil-nep_3.html', destination: '/ennodu-vaa-vaa-endru-lyrics-in-tamil-nep.html', permanent: true },
{ source: '/sayndhu-sayndhu-lyrics-in-tamil-nep_3.html', destination: '/sayndhu-sayndhu-lyrics-in-tamil-nep.html', permanent: true },
{ source: '/sayndhu-sayndhu-lyrics-neethaane-en_1.html', destination: '/sayndhu-sayndhu-lyrics-neethaane-en.html', permanent: true },
{ source: '/ennodu-vaa-vaa-lyrics-neethaane-en_1.html', destination: '/ennodu-vaa-vaa-lyrics-neethaane-en.html', permanent: true },
{ source: '/mudhal-murai-lyrics-neethaane-en_1.html', destination: '/mudhal-murai-lyrics-neethaane-en.html', permanent: true },
{ source: '/sattru-munbu-lyrics-neethaane-en_1.html', destination: '/sattru-munbu-lyrics-neethaane-en.html', permanent: true },
{ source: '/neethaane-en-ponvasantham-songs-lyrics_1.html', destination: '/neethaane-en-ponvasantham-songs-lyrics.html', permanent: true },
{ source: '/kaatrai-konjam-lyrics-in-tamil_30.html', destination: '/kaatrai-konjam-lyrics-in-tamil.html', permanent: true },
{ source: '/kaatrai-konjam-lyrics-neethane-en_30.html', destination: '/kaatrai-konjam-lyrics-neethane-en.html', permanent: true },
{ source: '/google-google-lyrics-in-tamil-thuppaki_14.html', destination: '/google-google-lyrics-in-tamil-thuppaki.html', permanent: true },
{ source: '/hare-rama-hare-krishna-lyrics-poda-podi_12.html', destination: '/hare-rama-hare-krishna-lyrics-poda-podi.html', permanent: true },
{ source: '/un-paarvaiyilae-lyrics-podaa-podi-songs_12.html', destination: '/un-paarvaiyilae-lyrics-podaa-podi-songs.html', permanent: true },
{ source: '/aiyyayo-maattikittenae-lyrics-podaa_12.html', destination: '/aiyyayo-maattikittenae-lyrics-podaa.html', permanent: true },
{ source: '/antartica-lyrics-in-tamil-thuppaki_11.html', destination: '/antartica-lyrics-in-tamil-thuppaki.html', permanent: true },
{ source: '/vennilave-lyrics-in-tamil-thuppaki_11.html', destination: '/vennilave-lyrics-in-tamil-thuppaki.html', permanent: true },
{ source: '/vennilave-tharayil-lyrics-thuppaki_11.html', destination: '/vennilave-tharayil-lyrics-thuppaki.html', permanent: true },
{ source: '/alaikaa-laikka-lyrics-thuppakki-songs_11.html', destination: '/alaikaa-laikka-lyrics-thuppakki-songs.html', permanent: true },
{ source: '/poi-varavaa-lyrics-thuppakki-songs_10.html', destination: '/poi-varavaa-lyrics-thuppakki-songs.html', permanent: true },
{ source: '/antartica-song-lyrics-thuppakki-songs_10.html', destination: '/antartica-song-lyrics-thuppakki-songs.html', permanent: true },
{ source: '/podaa-podi-kadhalai-lyrics-podaa-podi_10.html', destination: '/podaa-podi-kadhalai-lyrics-podaa-podi.html', permanent: true },
{ source: '/podaa-podi-songs-lyrics-track-list_10.html', destination: '/podaa-podi-songs-lyrics-track-list.html', permanent: true },
{ source: '/google-google-lyrics-thuppaki-songs_10.html', destination: '/google-google-lyrics-thuppaki-songs.html', permanent: true },
{ source: '/kutti-puli-kootam-lyrics-thuppakki_9.html', destination: '/kutti-puli-kootam-lyrics-thuppakki.html', permanent: true },
{ source: '/eisalaamey-eisalaam-lyrics-aadhi_7.html', destination: '/eisalaamey-eisalaam-lyrics-aadhi.html', permanent: true },
{ source: '/agadam-bagadam-lyrics-aadhi-bhagavan_7.html', destination: '/agadam-bagadam-lyrics-aadhi-bhagavan.html', permanent: true },
{ source: '/kaatriley-nadanthene-lyrics-aadhi_7.html', destination: '/kaatriley-nadanthene-lyrics-aadhi.html', permanent: true },
{ source: '/oru-thuli-vishamaai-lyrics-aadhi_7.html', destination: '/oru-thuli-vishamaai-lyrics-aadhi.html', permanent: true },
{ source: '/yaavum-poithaanaa-lyrics-aadhi-bhagavan_7.html', destination: '/yaavum-poithaanaa-lyrics-aadhi-bhagavan.html', permanent: true },
{ source: '/aadhi-bhagavan-rap-song-lyrics_7.html', destination: '/aadhi-bhagavan-rap-song-lyrics.html', permanent: true },
{ source: '/vellakuthira-lyrics-haridas-songs-lyrics_3.html', destination: '/vellakuthira-lyrics-haridas-songs-lyrics.html', permanent: true },
{ source: '/haridas-songs-lyrics_3.html', destination: '/haridas-songs-lyrics.html', permanent: true },
{ source: '/aaha-kaadhal-lyrics-moondru-per-moondru_2.html', destination: '/aaha-kaadhal-lyrics-moondru-per-moondru.html', permanent: true },
{ source: '/mazhai-mazhai-lyrics-moondru-per_2.html', destination: '/mazhai-mazhai-lyrics-moondru-per.html', permanent: true },
{ source: '/padapadakkudhu-lyrics-moondru-per_2.html', destination: '/padapadakkudhu-lyrics-moondru-per.html', permanent: true },
{ source: '/unakkagave-uyir-vaalgiren-lyrics_2.html', destination: '/unakkagave-uyir-vaalgiren-lyrics.html', permanent: true },
{ source: '/kaadhal-enthan-kaadhal-lyrics-moondru_2.html', destination: '/kaadhal-enthan-kaadhal-lyrics-moondru.html', permanent: true },
{ source: '/moondru-per-moondru-kadhal-lyrics_2.html', destination: '/moondru-per-moondru-kadhal-lyrics.html', permanent: true },
{ source: '/para-para-paravai-ondru-lyrics_1.html', destination: '/para-para-paravai-ondru-lyrics.html', permanent: true },
{ source: '/senneer-thaana-lyrics-in-tamil-paradesi_29.html', destination: '/senneer-thaana-lyrics-in-tamil-paradesi.html', permanent: true },
{ source: '/or-mirugam-lyrics-in-tamil-paradesi_29.html', destination: '/or-mirugam-lyrics-in-tamil-paradesi.html', permanent: true },
{ source: '/senneer-thaana-lyrics-paradesi-songs_25.html', destination: '/senneer-thaana-lyrics-paradesi-songs.html', permanent: true },
{ source: '/thannai-thaane-lyrics-paradesi-songs_25.html', destination: '/thannai-thaane-lyrics-paradesi-songs.html', permanent: true },
{ source: '/or-mirugam-lyrics-paradesi-songs-lyrics_25.html', destination: '/or-mirugam-lyrics-paradesi-songs-lyrics.html', permanent: true },
{ source: '/avatha-paiyan-lyrics-paradesi-songs_24.html', destination: '/avatha-paiyan-lyrics-paradesi-songs.html', permanent: true },
{ source: '/paradesi-songs-lyrics_24.html', destination: '/paradesi-songs-lyrics.html', permanent: true },
{ source: '/poochaandi-paarvayila-lyrics-sattam-oru_23.html', destination: '/poochaandi-paarvayila-lyrics-sattam-oru.html', permanent: true },
{ source: '/thirumba-thirumba-lyrics-sattam-oru_23.html', destination: '/thirumba-thirumba-lyrics-sattam-oru.html', permanent: true },
{ source: '/kadal-nenjukulle-lyrics-in-tamil_4.html', destination: '/kadal-nenjukulle-lyrics-in-tamil.html', permanent: true },
{ source: '/nenjukulle-lyrics-kadal-songs-lyrics_3.html', destination: '/nenjukulle-lyrics-kadal-songs-lyrics.html', permanent: true },
{ source: '/boomi-enna-suthudhe-lyrics-ethir_14.html', destination: '/boomi-enna-suthudhe-lyrics-ethir.html', permanent: true },
{ source: '/thaka-thayya-lyrics-alex-pandian-songs_13.html', destination: '/thaka-thayya-lyrics-alex-pandian-songs.html', permanent: true },
{ source: '/bad-boy-lyrics-alex-pandian-songs-lyrics_13.html', destination: '/bad-boy-lyrics-alex-pandian-songs-lyrics.html', permanent: true },
{ source: '/alex-pandian-songs-lyrics_12.html', destination: '/alex-pandian-songs-lyrics.html', permanent: true },
{ source: '/elay-keechan-lyrics-kadal-songs-lyrics_9.html', destination: '/elay-keechan-lyrics-kadal-songs-lyrics.html', permanent: true },
{ source: '/thuppakki-engal-lyrics-in-tamil_9.html', destination: '/thuppakki-engal-lyrics-in-tamil.html', permanent: true },
{ source: '/anu-vidhaiththa-boomiyile-lyrics-in_9.html', destination: '/anu-vidhaiththa-boomiyile-lyrics-in.html', permanent: true },
{ source: '/viswaroopam-lyrics-in-tamil_9.html', destination: '/viswaroopam-lyrics-in-tamil.html', permanent: true },
{ source: '/anu-vidhaiththa-boomiyile-lyrics_8.html', destination: '/anu-vidhaiththa-boomiyile-lyrics.html', permanent: true },
{ source: '/viswaroopam-songs-lyrics-tracklist_8.html', destination: '/viswaroopam-songs-lyrics-tracklist.html', permanent: true },
{ source: '/thuppakki-engal-lyrics-viswaroopam_7.html', destination: '/thuppakki-engal-lyrics-viswaroopam.html', permanent: true },
{ source: '/viswaroopam-lyrics-vishwaroopam-songs_7.html', destination: '/viswaroopam-lyrics-vishwaroopam-songs.html', permanent: true },
{ source: '/unnai-kaanadhu-naan-lyrics-vishwaroopam_7.html', destination: '/unnai-kaanadhu-naan-lyrics-vishwaroopam.html', permanent: true },
{ source: '/vellai-mayil-lyrics-samar-songs-lyrics_5.html', destination: '/vellai-mayil-lyrics-samar-songs-lyrics.html', permanent: true },
{ source: '/poikkaal-kuthirai-lyrics-samar-songs_5.html', destination: '/poikkaal-kuthirai-lyrics-samar-songs.html', permanent: true },
{ source: '/azhagho-azhaghu-lyrics-samar-songs_5.html', destination: '/azhagho-azhaghu-lyrics-samar-songs.html', permanent: true },
{ source: '/samar-songs-lyrics_4.html', destination: '/samar-songs-lyrics.html', permanent: true },
{ source: '/police-lyrics-haridas-songs-lyrics_3.html', destination: '/police-lyrics-haridas-songs-lyrics.html', permanent: true },
{ source: '/vazhkaiye-lyrics-haridas-songs-lyrics_3.html', destination: '/vazhkaiye-lyrics-haridas-songs-lyrics.html', permanent: true },
{ source: '/annaiyin-karuvil-lyrics-haridas-songs_3.html', destination: '/annaiyin-karuvil-lyrics-haridas-songs.html', permanent: true },
{ source: '/david-songs-lyrics-tamil_3.html', destination: '/david-songs-lyrics-tamil.html', permanent: true },
{ source: '/nijamellam-maranthupochu-lyrics-ethir_30.html', destination: '/nijamellam-maranthupochu-lyrics-ethir.html', permanent: true },
{ source: '/stop-paatu-lyrics-moondru-per-moondru_30.html', destination: '/stop-paatu-lyrics-moondru-per-moondru.html', permanent: true },
{ source: '/sattam-oru-iruttarai-songs-lyrics_23.html', destination: '/sattam-oru-iruttarai-songs-lyrics.html', permanent: true },
{ source: '/chithirai-nela-lyrics-in-tamil-kadal_23.html', destination: '/chithirai-nela-lyrics-in-tamil-kadal.html', permanent: true },
{ source: '/adiye-lyrics-in-tamil-english_23.html', destination: '/adiye-lyrics-in-tamil-english.html', permanent: true },
{ source: '/magudi-magudi-lyrics-kadal-songs-lyrics_15.html', destination: '/magudi-magudi-lyrics-kadal-songs-lyrics.html', permanent: true },
{ source: '/adiye-lyrics-in-tamil-kadal_15.html', destination: '/adiye-lyrics-in-tamil-kadal.html', permanent: true },
{ source: '/kadal-songs-lyrics_15.html', destination: '/kadal-songs-lyrics.html', permanent: true },
{ source: '/chithirai-nela-lyrics-kadal-songs-lyrics_15.html', destination: '/chithirai-nela-lyrics-kadal-songs-lyrics.html', permanent: true },
{ source: '/adiye-lyrics-kadal-songs-lyrics_15.html', destination: '/adiye-lyrics-kadal-songs-lyrics.html', permanent: true },
{ source: '/moongil-thottam-lyrics-kadal-songs_15.html', destination: '/moongil-thottam-lyrics-kadal-songs.html', permanent: true },
{ source: '/un-paarvayil-lyrics-ethir-neechal-songs_14.html', destination: '/un-paarvayil-lyrics-ethir-neechal-songs.html', permanent: true },
{ source: '/ethir-neechal-songs-lyrics_14.html', destination: '/ethir-neechal-songs-lyrics.html', permanent: true },
{ source: '/edhir-neechal-lyrics-ethir-neechal_14.html', destination: '/edhir-neechal-lyrics-ethir-neechal.html', permanent: true },
{ source: '/velicha-poove-lyrics-ethir-neechal_14.html', destination: '/velicha-poove-lyrics-ethir-neechal.html', permanent: true },
{ source: '/agalaadhe-agalathey-lyrics-settai-songs_11.html', destination: '/agalaadhe-agalathey-lyrics-settai-songs.html', permanent: true },
{ source: '/laila-laila-lyrics-settai-songs-lyrics_11.html', destination: '/laila-laila-lyrics-settai-songs-lyrics.html', permanent: true },
{ source: '/pothi-vecha-lyrics-annakodiyum_10.html', destination: '/pothi-vecha-lyrics-annakodiyum.html', permanent: true },
{ source: '/poraale-lyrics-annakodiyum-kodiveeranum_9.html', destination: '/poraale-lyrics-annakodiyum-kodiveeranum.html', permanent: true },
{ source: '/annakodiyum-kodiveeranum-songs-lyrics_9.html', destination: '/annakodiyum-kodiveeranum-songs-lyrics.html', permanent: true },
{ source: '/kedi-billa-killadi-ranga-songs-lyrics_6.html', destination: '/kedi-billa-killadi-ranga-songs-lyrics.html', permanent: true },
{ source: '/edhathaan-kanduttey-nee-pudhusa-lyrics_2.html', destination: '/edhathaan-kanduttey-nee-pudhusa-lyrics.html', permanent: true },
{ source: '/settai-songs-lyrics_27.html', destination: '/settai-songs-lyrics.html', permanent: true },
{ source: '/rajaavin-thoattathil-lyrics-samar-songs_13.html', destination: '/rajaavin-thoattathil-lyrics-samar-songs.html', permanent: true },
{ source: '/oru-kannil-vegam-lyrics-samar-songs_13.html', destination: '/oru-kannil-vegam-lyrics-samar-songs.html', permanent: true },
{ source: '/nee-dhana-lyrics-madha-gaja-raja-songs_13.html', destination: '/nee-dhana-lyrics-madha-gaja-raja-songs.html', permanent: true },
{ source: '/thumbakki-thumbai-lyrics-madha-gaja_13.html', destination: '/thumbakki-thumbai-lyrics-madha-gaja.html', permanent: true },
{ source: '/madha-gaja-raja-songs-lyrics_13.html', destination: '/madha-gaja-raja-songs-lyrics.html', permanent: true },
{ source: '/satrumun-lyrics-madha-gaja-raja-songs_13.html', destination: '/satrumun-lyrics-madha-gaja-raja-songs.html', permanent: true },
{ source: '/manamey-lyrics-david-songs-lyrics_4.html', destination: '/manamey-lyrics-david-songs-lyrics.html', permanent: true },
{ source: '/iruvanil-ulavavaa-lyrics-david-songs_4.html', destination: '/iruvanil-ulavavaa-lyrics-david-songs.html', permanent: true },
{ source: '/vazhkaiye-lyrics-david-songs-lyrics_3.html', destination: '/vazhkaiye-lyrics-david-songs-lyrics.html', permanent: true },
{ source: '/maria-pitache-lyrics-david-songs-lyrics_3.html', destination: '/maria-pitache-lyrics-david-songs-lyrics.html', permanent: true },
{ source: '/kanave-kanave-lyrics-david-songs-lyrics_3.html', destination: '/kanave-kanave-lyrics-david-songs-lyrics.html', permanent: true },
{ source: '/thanga-meengal-songs-lyrics_1.html', destination: '/thanga-meengal-songs-lyrics.html', permanent: true },
{ source: '/vaangana-vanakangana-lyrics-thalaivaa_1.html', destination: '/vaangana-vanakangana-lyrics-thalaivaa.html', permanent: true },
{ source: '/elavu-lyrics-aindhu-aindhu-aindhu-songs_7.html', destination: '/elavu-lyrics-aindhu-aindhu-aindhu-songs.html', permanent: true },
{ source: '/maali-pon-maalai-lyics-udhayam-nh4_4.html', destination: '/maali-pon-maalai-lyics-udhayam-nh4.html', permanent: true },
{ source: '/ora-kannaala-lyrics-udhayam-nh4-songs_4.html', destination: '/ora-kannaala-lyrics-udhayam-nh4-songs.html', permanent: true },
{ source: '/udhayam-nh4-songs-lyrics_31.html', destination: '/udhayam-nh4-songs-lyrics.html', permanent: true },
{ source: '/yaaro-ivan-lyrics-udhayam-nh4-songs_31.html', destination: '/yaaro-ivan-lyrics-udhayam-nh4-songs.html', permanent: true },
{ source: '/adutha-paruppu-lyrics-rendavudhu-padam_11.html', destination: '/adutha-paruppu-lyrics-rendavudhu-padam.html', permanent: true },
{ source: '/dheivangal-ellam-lyrics-kedi-billa_10.html', destination: '/dheivangal-ellam-lyrics-kedi-billa.html', permanent: true },
{ source: '/sudasuda-thooral-lyrics-kedi-billa_10.html', destination: '/sudasuda-thooral-lyrics-kedi-billa.html', permanent: true },
{ source: '/oru-porambokku-lyrics-kedi-billa_10.html', destination: '/oru-porambokku-lyrics-kedi-billa.html', permanent: true },
{ source: '/konjum-kili-lyrics-kedi-billa-killadi_10.html', destination: '/konjum-kili-lyrics-kedi-billa-killadi.html', permanent: true },
{ source: '/love-endravan-lyrics-vaalu-songs-lyrics_17.html', destination: '/love-endravan-lyrics-vaalu-songs-lyrics.html', permanent: true },
{ source: '/vathikuchi-songs-lyrics_11.html', destination: '/vathikuchi-songs-lyrics.html', permanent: true },
{ source: '/arjuna-arjuna-lyrics-settai-songs-lyrics_11.html', destination: '/arjuna-arjuna-lyrics-settai-songs-lyrics.html', permanent: true },
{ source: '/poyum-poyum-lyrics-settai-songs-lyrics_11.html', destination: '/poyum-poyum-lyrics-settai-songs-lyrics.html', permanent: true },
{ source: '/singam-2-songs-lyrics-tracklist_2.html', destination: '/singam-2-songs-lyrics-tracklist.html', permanent: true },
{ source: '/kai-pesi-lyrics-thillu-mullu-songs_2.html', destination: '/kai-pesi-lyrics-thillu-mullu-songs.html', permanent: true },
{ source: '/thillu-mullu-thillu-mullu-lyrics-thillu_2.html', destination: '/thillu-mullu-thillu-mullu-lyrics-thillu.html', permanent: true },
{ source: '/thillu-mullu-song-lyrics_2.html', destination: '/thillu-mullu-song-lyrics.html', permanent: true },
{ source: '/en-chella-kutti-lyrics-isakki-song_27.html', destination: '/en-chella-kutti-lyrics-isakki-song.html', permanent: true },
{ source: '/aruvaakkaaran-lyrics-kutti-puli-songs_27.html', destination: '/aruvaakkaaran-lyrics-kutti-puli-songs.html', permanent: true },
{ source: '/kadhal-ennulle-lyrics-neram-songs-lyrics_27.html', destination: '/kadhal-ennulle-lyrics-neram-songs-lyrics.html', permanent: true },
{ source: '/i-love-my-africa-lyrics-mariyaan-songs_19.html', destination: '/i-love-my-africa-lyrics-mariyaan-songs.html', permanent: true },
{ source: '/yenga-pona-raasa-lyrics-mariyaan-songs_19.html', destination: '/yenga-pona-raasa-lyrics-mariyaan-songs.html', permanent: true },
{ source: '/nenje-ezhu-lyrics-mariyaan-songs-lyrics_15.html', destination: '/nenje-ezhu-lyrics-mariyaan-songs-lyrics.html', permanent: true },
{ source: '/mariyaan-songs-lyrics-tracklist_15.html', destination: '/mariyaan-songs-lyrics-tracklist.html', permanent: true },
{ source: '/sonapareeya-lyrics-mariyaan-songs-lyrics_15.html', destination: '/sonapareeya-lyrics-mariyaan-songs-lyrics.html', permanent: true },
{ source: '/kadal-raasa-lyrics-mariyaan-songs-lyrics_14.html', destination: '/kadal-raasa-lyrics-mariyaan-songs-lyrics.html', permanent: true },
{ source: '/netru-aval-lyrics-mariyaan-songs-lyrics_14.html', destination: '/netru-aval-lyrics-mariyaan-songs-lyrics.html', permanent: true },
{ source: '/innum-konjam-neram-lyrics-mariyaan_14.html', destination: '/innum-konjam-neram-lyrics-mariyaan.html', permanent: true },
{ source: '/aanandha-yazhai-lyrics-thanga-meengal_9.html', destination: '/aanandha-yazhai-lyrics-thanga-meengal.html', permanent: true },
{ source: '/thirutu-pasanga-lyrics-theeya-velai_4.html', destination: '/thirutu-pasanga-lyrics-theeya-velai.html', permanent: true },
{ source: '/theeya-velai-seiyyanum-kumaru-songs_4.html', destination: '/theeya-velai-seiyyanum-kumaru-songs.html', permanent: true },
{ source: '/azhagendral-lyrics-theeya-velai_4.html', destination: '/azhagendral-lyrics-theeya-velai.html', permanent: true },
{ source: '/kozhu-kozhu-lyrics-theeya-velai_4.html', destination: '/kozhu-kozhu-lyrics-theeya-velai.html', permanent: true },
{ source: '/vu-songs-lyrics_7.html', destination: '/vu-songs-lyrics.html', permanent: true },
{ source: '/thikki-thenarudhu-devathai-lyrics-vu_7.html', destination: '/thikki-thenarudhu-devathai-lyrics-vu.html', permanent: true },
{ source: '/chinna-kuzhandhai-lyrics-vu-songs-lyrics_7.html', destination: '/chinna-kuzhandhai-lyrics-vu-songs-lyrics.html', permanent: true },
{ source: '/pattathu-yaanai-songs-lyrics_26.html', destination: '/pattathu-yaanai-songs-lyrics.html', permanent: true },
{ source: '/enna-oru-enna-oru-lyrics-pattathu_24.html', destination: '/enna-oru-enna-oru-lyrics-pattathu.html', permanent: true },
{ source: '/thala-kaalu-puriyala-lyrics-pattathu_24.html', destination: '/thala-kaalu-puriyala-lyrics-pattathu.html', permanent: true },
{ source: '/kalaarasiga-lyrics-ambikapathy-songs_23.html', destination: '/kalaarasiga-lyrics-ambikapathy-songs.html', permanent: true },
{ source: '/ambikapathy-songs-lyrics_23.html', destination: '/ambikapathy-songs-lyrics.html', permanent: true },
{ source: '/paarkaadhey-lyrics-ambikapathy-songs_23.html', destination: '/paarkaadhey-lyrics-ambikapathy-songs.html', permanent: true },
{ source: '/ambikapathy-lyrics-ambikapathy-songs_23.html', destination: '/ambikapathy-lyrics-ambikapathy-songs.html', permanent: true },
{ source: '/yaar-indha-saalai-oram-lyrics-thalaivaa_19.html', destination: '/yaar-indha-saalai-oram-lyrics-thalaivaa.html', permanent: true },
{ source: '/tamil-pasanga-lyrics-thalaivaa-songs_19.html', destination: '/tamil-pasanga-lyrics-thalaivaa-songs.html', permanent: true },
{ source: '/sol-sol-lyrics-thalaivaa-songs-lyrics_19.html', destination: '/sol-sol-lyrics-thalaivaa-songs-lyrics.html', permanent: true },
{ source: '/thalaivaa-thalaivaa-lyrics-thalaivaa_19.html', destination: '/thalaivaa-thalaivaa-lyrics-thalaivaa.html', permanent: true },
{ source: '/thalaivaa-songs-lyrics-track-list_4.html', destination: '/thalaivaa-songs-lyrics-track-list.html', permanent: true },
{ source: '/kannukulle-lyrics-singam-2-songs-lyrics_3.html', destination: '/kannukulle-lyrics-singam-2-songs-lyrics.html', permanent: true },
{ source: '/singam-dance-lyrics-singam-2-songs_2.html', destination: '/singam-dance-lyrics-singam-2-songs.html', permanent: true },
{ source: '/puriya-villai-lyrics-singam-2-songs_2.html', destination: '/puriya-villai-lyrics-singam-2-songs.html', permanent: true },
{ source: '/mannavane-en-mannavane-lyrics-irandam_9.html', destination: '/mannavane-en-mannavane-lyrics-irandam.html', permanent: true },
{ source: '/kanimozhiye-lyrics-irandam-ulagam-song_9.html', destination: '/kanimozhiye-lyrics-irandam-ulagam-song.html', permanent: true },
{ source: '/pazhangalla-vishamulla-lyrics-irandam_5.html', destination: '/pazhangalla-vishamulla-lyrics-irandam.html', permanent: true },
{ source: '/irandam-ulagam-songs-lyrics_5.html', destination: '/irandam-ulagam-songs-lyrics.html', permanent: true },
{ source: '/vinnaithaandi-lyrics-irandam-ulagam_5.html', destination: '/vinnaithaandi-lyrics-irandam-ulagam.html', permanent: true },
{ source: '/osaka-osaka-lyrics-vanakkam-chennai_28.html', destination: '/osaka-osaka-lyrics-vanakkam-chennai.html', permanent: true },
{ source: '/chennai-city-gangsta-lyrics-vanakkam_28.html', destination: '/chennai-city-gangsta-lyrics-vanakkam.html', permanent: true },
{ source: '/oh-penne-lyrics-vanakkam-chennai-song_28.html', destination: '/oh-penne-lyrics-vanakkam-chennai-song.html', permanent: true },
{ source: '/engadi-porandha-lyrics-vanakkam-chennai_28.html', destination: '/engadi-porandha-lyrics-vanakkam-chennai.html', permanent: true },
{ source: '/ailasa-ailasa-lyrics-vanakkam-chennai_28.html', destination: '/ailasa-ailasa-lyrics-vanakkam-chennai.html', permanent: true },
{ source: '/yennada-yennada-lyrics-varutha-padatha_22.html', destination: '/yennada-yennada-lyrics-varutha-padatha.html', permanent: true },
{ source: '/varutha-padatha-vaalibar-sangam-songs_13.html', destination: '/varutha-padatha-vaalibar-sangam-songs.html', permanent: true },
{ source: '/indha-ponnugale-lyrics-varuthapadatha_13.html', destination: '/indha-ponnugale-lyrics-varuthapadatha.html', permanent: true },
{ source: '/paarkathe-paarkathe-lyrics_12.html', destination: '/paarkathe-paarkathe-lyrics.html', permanent: true },
{ source: '/thamirabarani-lyrics-nedunchalai-songs_7.html', destination: '/thamirabarani-lyrics-nedunchalai-songs.html', permanent: true },
{ source: '/nedunchalai-songs-lyrics_7.html', destination: '/nedunchalai-songs-lyrics.html', permanent: true },
{ source: '/ivan-yaaro-lyrics-nedunchalai-songs_7.html', destination: '/ivan-yaaro-lyrics-nedunchalai-songs.html', permanent: true },
{ source: '/injathae-lyrics-nedunchalai-songs-lyrics_7.html', destination: '/injathae-lyrics-nedunchalai-songs-lyrics.html', permanent: true },
{ source: '/nandooruthu-lyrics-nedunchalai-songs_7.html', destination: '/nandooruthu-lyrics-nedunchalai-songs.html', permanent: true },
{ source: '/vaigai-nathi-lyrics-nedunchalai-songs_7.html', destination: '/vaigai-nathi-lyrics-nedunchalai-songs.html', permanent: true },
{ source: '/adadada-arrambame-lyrics-arrambam-song_18.html', destination: '/adadada-arrambame-lyrics-arrambam-song.html', permanent: true },
{ source: '/ya-ya-song-lyrics_18.html', destination: '/ya-ya-song-lyrics.html', permanent: true },
{ source: '/friende-podhum-lyrics-ya-ya-song-lyrics_18.html', destination: '/friende-podhum-lyrics-ya-ya-song-lyrics.html', permanent: true },
{ source: '/oru-kannadiya-lyrics-ya-ya-song-lyrics_18.html', destination: '/oru-kannadiya-lyrics-ya-ya-song-lyrics.html', permanent: true },
{ source: '/moodar-koodam-song-lyrics_15.html', destination: '/moodar-koodam-song-lyrics.html', permanent: true },
{ source: '/abcd-ungappan-dhadi-lyrics-moodar_15.html', destination: '/abcd-ungappan-dhadi-lyrics-moodar.html', permanent: true },
{ source: '/neeyum-bommai-lyrics-moodar-koodam-song_15.html', destination: '/neeyum-bommai-lyrics-moodar-koodam-song.html', permanent: true },
{ source: '/boomiyil-lyrics-pizza-2-villa-song_8.html', destination: '/boomiyil-lyrics-pizza-2-villa-song.html', permanent: true },
{ source: '/nadhi-vellam-lyrics-thanga-meengal-song_7.html', destination: '/nadhi-vellam-lyrics-thanga-meengal-song.html', permanent: true },
{ source: '/oday-oday-lyrics-raja-rani-song-lyrics_24.html', destination: '/oday-oday-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/chillena-lyrics-raja-rani-song-lyrics_24.html', destination: '/chillena-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/angnyaade-lyrics-raja-rani-song-lyrics_24.html', destination: '/angnyaade-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/imaye-imaye-lyrics-raja-rani-song-lyrics_24.html', destination: '/imaye-imaye-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/unnale-lyrics-raja-rani-song-lyrics_24.html', destination: '/unnale-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/hey-baby-lyrics-raja-rani-song-lyrics_21.html', destination: '/hey-baby-lyrics-raja-rani-song-lyrics.html', permanent: true },
{ source: '/biriyani-songs-lyrics_17.html', destination: '/biriyani-songs-lyrics.html', permanent: true },
{ source: '/biriyani-lyrics-biriyani-song-lyrics_17.html', destination: '/biriyani-lyrics-biriyani-song-lyrics.html', permanent: true },
{ source: '/edhirthu-nil-lyrics-biriyani-song-lyrics_17.html', destination: '/edhirthu-nil-lyrics-biriyani-song-lyrics.html', permanent: true },
{ source: '/en-kadhal-thee-lyrics-irandam-ulagam_9.html', destination: '/en-kadhal-thee-lyrics-irandam-ulagam.html', permanent: true },
{ source: '/naiyaandi-songs-lyrics_10.html', destination: '/naiyaandi-songs-lyrics.html', permanent: true },
{ source: '/en-veetula-lyrics-idharkuthane_2.html', destination: '/en-veetula-lyrics-idharkuthane.html', permanent: true },
{ source: '/yen-endral-lyrics-idharkuthane_2.html', destination: '/yen-endral-lyrics-idharkuthane.html', permanent: true },
{ source: '/idharkuthane-aasaipattai-balakumara_2.html', destination: '/idharkuthane-aasaipattai-balakumara.html', permanent: true },
{ source: '/raja-rani-song-lyrics_27.html', destination: '/raja-rani-song-lyrics.html', permanent: true },
{ source: '/othakada-lyrics-pandiya-nadu-song-lyrics_25.html', destination: '/othakada-lyrics-pandiya-nadu-song-lyrics.html', permanent: true },
{ source: '/yendi-paathagathi-lyrics-naiyaandi-song_20.html', destination: '/yendi-paathagathi-lyrics-naiyaandi-song.html', permanent: true },
{ source: '/ae-le-le-etti-paarthale-lyrics_20.html', destination: '/ae-le-le-etti-paarthale-lyrics.html', permanent: true },
{ source: '/teady-bear-lyrics-naiyaandi-song-lyrics_20.html', destination: '/teady-bear-lyrics-naiyaandi-song-lyrics.html', permanent: true },
{ source: '/melala-vedikudhu-lyrics-arrambam-song_18.html', destination: '/melala-vedikudhu-lyrics-arrambam-song.html', permanent: true },
{ source: '/hare-rama-lyrics-arrambam-song-lyrics_18.html', destination: '/hare-rama-lyrics-arrambam-song-lyrics.html', permanent: true },
{ source: '/en-fuse-pochu-lyrics-arrambam-song_18.html', destination: '/en-fuse-pochu-lyrics-arrambam-song.html', permanent: true },
{ source: '/stylish-thamizhachi-lyrics-arrambam_18.html', destination: '/stylish-thamizhachi-lyrics-arrambam.html', permanent: true },
{ source: '/i-song-lyrics.html', destination: '/i-song-lyrics-with-english-meaning.html', permanent: true },
{ source: '/thara-local-boys-lyrics-maari-song.html', destination: '/maari-thara-local-lyrics-maari-song.html', permanent: true },
{ source: '/neeye-vaazhkai-enben-lyrics-english-meaning.html', destination: '/neeye-vaazhkai-enben--lyrics-english-meaning.html', permanent: true },
{ source: '/kaththi-sandai-song-lyrics_30.html', destination: '/kaththi-sandai-song-lyrics.html', permanent: true },
{ source: '/trend-song-song-lyrics-aaa-aka.html', destination: '/song-song-lyrics-aaa-aka-anbanavan.html', permanent: true },
{ source: '/8-thottakkal-songs-lyrics.html', destination: '/', permanent: true },
{ source: '/thaana-serndha-koottam-promo-lyrics-tsk.html', destination: '/', permanent: true },
{ source: '/saravanan-irukka-bayamaen-songs-lyrics.html', destination: '/saravanan-irukka-bayamaen-songs-lyrics_31.html', permanent: true },
{ source: '/langu-langu-lyrics-saravanan-irukka.html', destination: '/langu-langu-lyrics-saravanan-irukka_31.html', permanent: true },
{ source: '/lala-kadai-shanthi-lyrics-saravanan.html', destination: '/lala-kadai-shanthi-lyrics-saravanan_31.html', permanent: true },
{ source: '/marhaba-aavona-lyrics-saravanan-irukka.html', destination: '/marhaba-aavona-lyrics-saravanan-irukka_31.html', permanent: true },
{ source: '/embuttu-irukkuthu-aasai-lyrics.html', destination: '/embuttu-irukkuthu-aasai-lyrics_31.html', permanent: true },
{ source: '/naan-pizhaippeno-lyrics-english-meaning.html', destination: '/naan-pizhaippeno-lyrics-english-meaning_31.html', permanent: true },
{ source: '/anbullam-konda-ammavukku-lyrics-album.html', destination: '/anbullam-konda-ammavukku-lyrics-album_31.html', permanent: true },
{ source: '/mersal-song-lyrics.html', destination: '/', permanent: true },
{ source: '/velaikkaran-single-song-lyrics.html', destination: '/', permanent: true },
{ source: '/macho-lyrics-mersal.html', destination: '/maacho-lyrics-mersal.html', permanent: true },
{ source: '/mersal-neethanae-lyrics-english-meaning.html', destination: '/neethanae-lyrics-english-meaning.html', permanent: true },
{ source: '/neethanae-lyrics-mersal.html', destination: '/neethane-neethane-lyrics-in-tamil-from.html', permanent: true },
{ source: '/vanamagan-songs-tracklist.html', destination: '/vanamagan-songs-lyrics.html', permanent: true },
{ source: '/guleba-sokama-sokama-lyrics.html', destination: '/guleba-song-lyrics-gulebagavali.html', permanent: true },
{ source: '/enge-endru-povadhu-lyrics.html', destination: '/enge-endru-povadhu-lyrics-tsk.html', permanent: true },
{ source: '/demonetization-anthem-lyrics-album.html', destination: '/demonetization-anthem-lyrics-thatrom.html', permanent: true },
{ source: '/heartukulla-pachkuthiye-lyrics.html', destination: '/heartukulla-pachkuthiye-lyrics_01673865731.html', permanent: true },
{ source: '/enga-veetu-kuththu-vizhakku-lyrics.html', destination: '/enga-veetu-kuththu-vilakku-lyrics.html', permanent: true },
{ source: '/seramal-ponal-lyrics-gulaebaghavali.html', destination: '/seramal-ponal-lyrics-gulebagavali.html', permanent: true },
{ source: '/vishwaroopam-2-songs-lyrics.html', destination: '/', permanent: true },
{ source: '/kaatre-un-kaladiyai-dope-track-lyrics.html', destination: '/kaatre-un-kaladiyai-dope-track-pyaar.html', permanent: true },
{ source: '/kannamma-lyrics-english-meaning.html', destination: '/kaala-kannamma-lyrics-english-meaning.html', permanent: true },
{ source: '/theruvilakku-velichathula-lyrics-kaala.html', destination: '/', permanent: true },
{ source: '/nikkal-nikkal-lyrics-kaala.html', destination: '/nikkal-nikkal-kelambuda-lyrics-kaala.html', permanent: true },
{ source: '/poraduvom-lyrics-kaala.html', destination: '/', permanent: true },
{ source: '/96-movie-teaser-songs-lyrics-tamil.html', destination: '/', permanent: true },
{ source: '/peipasi-songs-lyrics-tamil-movie.html', destination: '/', permanent: true },
{ source: '/ethuvarai-pogalam-lyrics-enai-noki.html', destination: '/ethuvarai-pogalam-lyrics-in-tamil.html', permanent: true },
{ source: '/maruvarthai-pesathe-song-lyrics-enai-2.html', destination: '/maruvarthai-pesathe-song-lyrics-in.html', permanent: true },
{ source: '/oru-lady-body-lyrics-semma-botha.html', destination: '/semma-botha-aagathey-lyrics-semma-botha.html', permanent: true },
{ source: '/vendam-kadhale-pothum-pothum-poi-vidu.html', destination: '/vendam-kadhal-pothum-pothum-poi-vidu.html', permanent: true },
{ source: '/kabiskaba-coco-lyrics-kolamaavu-kokila.html', destination: '/kabiskabaa-coco-lyrics-kolamaavu-kokila.html', permanent: true },
{ source: '/naanagiya-nadhimoolame-lyrics-vishwaroopam-2.html', destination: '/naanaagiya-nadhimoolame-lyrics.html', permanent: true },
{ source: '/kettavano-song-lyrics-7up-madras-gig-album-song.html', destination: '/kettavano-lyrics-7up-madras-gig-album.html', permanent: true },
{ source: '/periyar-kuthu-song-lyrics-by-simbu-album.html', destination: '/periyar-kuthu-song-lyrics.html', permanent: true },
{ source: '/hold-me-now-song-lyrics-pyaar-prema.html', destination: '/hold-me-now-hold-me-little-closer-song.html', permanent: true },
{ source: '/pyaar-prema-kaadhal-songs-lyrics.html', destination: '/', permanent: true },
{ source: '/saamy-square-songs-lyrics.html', destination: '/', permanent: true },
{ source: '/hey-penne-en-nenjil-song-lyrics-in-tamil-font.html', destination: '/hey-penne-en-nenjil-high-on-love-lyrics.html', permanent: true },
{ source: '/kadhalikathey-manase-lyrics-imaikkaa.html', destination: '/kadhalikathey-manase-lyrics-imaikka.html', permanent: true },
{ source: '/anthaathi-96-song-lyrics-english-meaning.html', destination: '/anthathi-96-song-lyrics-english-meaning.html', permanent: true },
{ source: '/othaiyadi-pathayila-lyrics-from-kanaa.html', destination: '/othaiyadi-pathaiyila-lyrics-from-kanaa.html', permanent: true },
{ source: '/unnai-vittal-unnai-vella-lyrics-from.html', destination: '/oonjala-oonjala-lyrics-kanaa-tamil-movie.html', permanent: true },
{ source: '/vaayadi-petha-pulla-lyrics-from-kanaa.html', destination: '/vayadi-petha-pulla-lyrics-from-kanaa.html', permanent: true },
{ source: '/anthaathi-nee-lyrics-from-96-movie.html', destination: '/anthathi-lyrics-from-96-movie.html', permanent: true },
{ source: '/sengarattan-paaraiyula-lyrics-sandakozhi-2.html', destination: '/sengarattan-paaraiyula-lyrics.html', permanent: true },
{ source: '/oru-manam-song-lyrics-from-dhruva-natchathiram.html', destination: '/oru-manam-upcoming-song-from-dhruva.html', permanent: true },
{ source: '/yaazhini-song-lyrics-from-titanic-tamil-movie.html', destination: '/yaazhini-en-yaazhini-lyrics-from.html', permanent: true },
{ source: '/innum-enna-onnum-vendame-inkem-inkem.html', destination: '/innum-enna-onnum-vendame-song-lyrics-in.html', permanent: true },
{ source: '/simtaangaran-english-meaning.html', destination: '/simtaangaran-song-lyrics-meaning-in.html', permanent: true },
{ source: '/goindhammavaala-song-lyrics-from-vada.html', destination: '/goindhammavaala-lyrics-from-vada-chennai.html', permanent: true },
{ source: '/iravingu-theevaai-song-lyrics-from-96.html', destination: '/iravingu-theevaai-96-song-lyrics.html', permanent: true },
{ source: '/yaen-yedhum-kooraamal-96-song-lyrics-in.html', destination: '/yen-yedhum-kooraamal-96-song-lyrics.html', permanent: true },
{ source: '/karai-vandha-pirage-song-lyrics.html', destination: '/karai-vandha-pirage-lyrics-96-movie.html', permanent: true },
{ source: '/sevandhu-pochu-nenju-lyrics-in-tamil-and-english-meaning.html', destination: '/sevandhu-pochu-nenju-lyrics-in-tamil.html', permanent: true },
{ source: '/bhoomi-bhoomi-song-lyrics-chekka-chivantha.html', destination: '/bhoomi-bhoomi-song-lyrics-chekka.html', permanent: true },
{ source: '/mazhai-kuruvi-neela-mazhai-saaral-song-lyrics.html', destination: '/mazhai-kuruvi-song-lyrics-from-chekka.html', permanent: true },
{ source: '/yaaradi-nee-song-lyrics-from-jarugandi-2018.html', destination: '/yaaradi-nee-lyrics-from-jarugandi.html', permanent: true },
{ source: '/adichu-thookku-song-lyrics-viswasam.html', destination: '/adichu-thooku-song-lyrics-from-viswasam.html', permanent: true },
{ source: '/ilamai-thirumbuthe-lyrics-in-tamil.html', destination: '/ilamai-thirumbuthe-lyrics-from-petta.html', permanent: true },
{ source: '/my-dear-machan-lyrics-maari-2.html', destination: '/my-dear-machan-song-lyrics-maari-2.html', permanent: true },
{ source: '/marana-mass-song-lyrics-english-meaning.html', destination: '/', permanent: true },
{ source: '/ullaalaa-song-lyrics-petta.html', destination: '/ullala-petta-song-lyrics.html', permanent: true },
{ source: '/marana-mass-song-lyrics-petta.html', destination: '/marana-mass-lyrics-from-petta.html', permanent: true },
{ source: '/rowdy-baby-song-lyrics-maari.html', destination: '/rowdy-baby-lyrics.html', permanent: true },
{ source: '/adi-vellakara-velayi-song-lyrics-tamil.html', destination: '/adi-vellakara-velayi-song-lyrics-in.html', permanent: true },
{ source: '/dope-antham-pongum-pugaiyile-song-lyrics-tamil.html', destination: '/dope-antham-lyrics-pongum-pugaiyile.html', permanent: true },
{ source: '/top-tucker-lyrics-tamil-sarkar-songs.html', destination: '/top-tuckeru-song-lyrics-sarkar.html', permanent: true },
{ source: '/ennadi-mayavi-nee-lyrics-in-tamil.html', destination: '/ennadi-mayavi-nee-lyrics-vada-chennai.html', permanent: true },
{ source: '/raja-raja-kula-lyrics-from-nota-tamil-movie.html', destination: '/raja-raja-kula-lyrics-nota-tamil-song.html', permanent: true },
{ source: '/oruviral-puratchi-song-lyrics-from-sarkar.html', destination: '/oruviral-puratchi-song-lyrics-from.html', permanent: true },
{ source: '/simtaangaran-lyrics-from-sarkar-tamil.html', destination: '/simtaangaran-lyrics-from-sarkar.html', permanent: true },
{ source: '/kannana-kanne-viswasam-song-lyrics-tamil.html', destination: '/kannana-kanne-viswasam-lyrics.html', permanent: true },
{ source: '/petta-paraak-song-lyrics-in-tamil.html', destination: '/petta-paraak-song-lyrics.html', permanent: true },
{ source: '/rowdy-baby-song-lyrics-english-meaning.html', destination: '/rowdy-baby-lyrics-meaning-in-english.html', permanent: true },
{ source: '/maari-anandhi-vaanam-pozhiyaama-song-lyrics.html', destination: '/maari-anandhi-vanam-pozhiyama-lyrics.html', permanent: true },
{ source: '/nee-nenacha-song-lyrics-tamil.html', destination: '/nee-nenacha-song-lyrics.html', permanent: true },
{ source: '/pularaadha-song-lyrics-in-tamil.html', destination: '/pularaadha-song-lyrics.html', permanent: true },
{ source: '/thandalkaaran-ngk-song-lyrics-tamil.html', destination: '/thandalkaaran-ngk-song-lyrics.html', permanent: true },
{ source: '/ayogya-kanne-kanne-song-lyrics-tamil.html', destination: '/kanne-kanne-unna-thooki-lyrics-in-tamil.html', permanent: true },
{ source: '/anbae-peranbae-ngk-song-lyrics-tamil.html', destination: '/anbe-pranbe-ngk-lyrics-tamil.html', permanent: true },
{ source: '/takkunu-takkunu-mr-local-lyrics-tamil.html', destination: '/takkunu-takkunu-mr-local-lyrics.html', permanent: true },
{ source: '/aagaasa-veedu-kattum-tamil-lyrics.html', destination: '/aagaasa-veedu-kattum-song-lyrics-tamil.html', permanent: true },
{ source: '/marvel-anthem-song-tamil-lyrics.html', destination: '/marvel-anthem-tamil-lyrics-avengers.html', permanent: true },
{ source: '/rasaathi-nenja-song-lyrics-tamil-7up-madras-gig.html', destination: '/rasaathi-nenja-song-lyrics-tamil-7up.html', permanent: true },
{ source: '/kannamma-unna-manasil-song-lyrics-tamil.html', destination: '/kannamma-unna-manasil-lyrics-in-tamil.html', permanent: true },
{ source: '/petta-paraak-meaning-english.html', destination: '/petta-paraak-meaning.html', permanent: true },
{ source: '/anbe-peranbu-lyrics-in-tamil.html', destination: '/anbe-anbin-peranbu-lyrics.html', permanent: true },
{ source: '/vera-ethuvum-thevai-illai-lyrics-thaarame.html', destination: '/thaarame-thaarame-vera-ethuvum-thevai.html', permanent: true },
{ source: '/agalathey-song-lyrics-in-tamil.html', destination: '/agalathey-song-lyrics.html', permanent: true },
{ source: '/singa-penne-song-lyrics-tamil.html', destination: '/singa-penne-lyrics-in-tamil.html', permanent: true },
{ source: '/gumbala-suthuvom-lyrics-gana-stephen.html', destination: '/gumbala-suthuvom-song-lyrics.html', permanent: true },
{ source: '/kathal-tholviya-pathavan-nanu-lyrics.html', destination: '/paisa-note-song-lyrics.html', permanent: true },
{ source: '/pularaadha-meaning.html', destination: '/', permanent: true },
{ source: '/hey-nijame-lyrics-from-enpt.html', destination: '/hey-nijame-lyrics-in-tamil.html', permanent: true },
{ source: '/adada-naana-lyrics-from-enpt.html', destination: '/adada-naana-lyrics-enpt.html', permanent: true },
{ source: '/kathari-poovazhagi-lyrics-asuran.html', destination: '/kathari-poovazhagi-lyrics.html', permanent: true },
{ source: '/pollaadha-boomi-lyrics-tamil-asuran.html', destination: '/pollaadha-boomi-lyrics-asuran.html', permanent: true },
{ source: '/verithanam-song-lyrics-tamil.html', destination: '/verithanam-lyrics-bigil.html', permanent: true },
{ source: '/verithanam-song-meaning.html', destination: '/verithanam-meaning.html', permanent: true },
{ source: '/unakkaga-vazha-ninaikiren-lyrics-tamil.html', destination: '/unakaaga-lyrics-bigil.html', permanent: true },
{ source: '/unnaale-ennaalum-song-lyrics-in-tamil.html', destination: '/unnaale-ennaalum-lyics.html', permanent: true },
{ source: '/maathare-song-lyrics-in-tamil.html', destination: '/maathare-maathare-lyrics.html', permanent: true },
{ source: '/railaa-railaa-song-lyrics-in-tamil.html', destination: '/railaa-railaa-lyrics.html', permanent: true },
{ source: '/neethan-neethan-mugen-lyrics-in-tamil.html', destination: '/neethaan-neethan-mugen-song-lyrics.html', permanent: true },
{ source: '/kutty-story-tamil-lyrics-master.html', destination: '/kutty-story-lyrics-from-master.html', permanent: true },
{ source: '/unna-nenachu-nenachu-song-lyrics-in-tamil.html', destination: '/unna-nenachu-nenachu-song-lyrics.html', permanent: true },
{ source: '/pathala-pathala-vikram-song-lyrics-tamil.html', destination: '/pathala-pathala-vikram-lyrics.html', permanent: true },
{ source: '/mehabooba-tamil-lyrics-kg2.html', destination: '/mehabooba-tamil-lyrics.html', permanent: true },
{ source: '/ini-nan-unna-en-kanna-pola-song-lyrics.html', destination: '/bae-ini-nan-unna-en-kanna-pola-lyrics.html', permanent: true },
{ source: '/heisenberg-lyrics-vikram.html', destination: '/once-upon-time-there-lived-ghost-lyrics.html', permanent: true },
{ source: '/vikram-title-song-lyrics-tamil.html', destination: '/vikram-title-song-lyrics.html', permanent: true },
{ source: '/thaiyaga-maariduven-song-lyrics-tamil.html', destination: '/thaya-maariduven-lyrics-dada.html', permanent: true },
{ source: '/jaragandi-tamil-lyrics.html', destination: '/jaragandi-tamil-lyrics-game-changer.html', permanent: true },
{ source: '/anbenum-aayudham-lyrics-tamil.html', destination: '/anbenum-leo.html', permanent: true },
{ source: '/kattazhagu-karuvaachi-lyrics-tamil.html', destination: '/kattazhagu-karuvaachi-lyrics-in-tamil.html', permanent: true },
{ source: '/we-are-not-the-same-tamil-lyrics.html', destination: '/we-are-not-same-soodhu-kavvum-2.html', permanent: true },
{ source: '/vintage-love-lyrics-in-tamil.html', destination: '/vintage-love-tamil-lyrics.html', permanent: true },
{ source: '/un-azhagai-rasithu-lyrics-in-tamil.html', destination: '/un-azhagai-rasithu-pon-ondru-kanden.html', permanent: true },
{ source: '/ennamma-ennamma-lyrics-pon-ondru-kanden.html', destination: '/ennamma-ennamma-pon-ondru-kanden.html', permanent: true },
{ source: '/thalavali-lyrics.html', destination: '/thalavali-lyrics-dear.html', permanent: true },
{ source: '/andha-aruvi-pola-song-lyrics.html', destination: '/andha-aruvi-pola-chithha.html', permanent: true },
{ source: '/whistle-podu-lyrics-tamil.html', destination: '/whistle-podu-goat.html', permanent: true },
{ source: '/coolie-disco-lyrics-teaser.html', destination: '/coolie-disco-lyrics.html', permanent: true },
{ source: '/chikitu-vibe-lyrics-coolie.html', destination: '/chikitu-song-lyrics-coolie.html', permanent: true },
{ source: '/vizhi-veekura-song-lyrics-in-tamil.html', destination: '/vizhi-veekura-lyrics.html', permanent: true },
{ source: '/monica-coolie-lyrics.html', destination: '/monica-lyrics-coolie.html', permanent: true }
];

// Load migration redirects
function loadMigrationRedirects() {
  try {
    const mappingPath = path.join(process.cwd(), 'migration_analysis', 'url_mappings_clean.json');
    if (fs.existsSync(mappingPath)) {
      const data = JSON.parse(fs.readFileSync(mappingPath, 'utf8'));
      return (data.redirects || [])
        .filter(mapping => 
          mapping.source !== mapping.destination &&
          mapping.source && mapping.destination &&
          mapping.score >= 0.8
        )
        .map(mapping => ({
          source: mapping.source,
          destination: mapping.destination,
          permanent: true
        }));
    }
  } catch (error) {
    console.error('Error loading migration redirects:', error);
  }
  return [];
}

const nextConfig = {
  images: {
    unoptimized: true, // Disable Vercel image optimization to avoid limit
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'blogger.googleusercontent.com',
      },
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
      },
      {
        protocol: 'https',
        hostname: 'img.youtube.com',
      },
    ],
    formats: ['image/webp'],
  },
  // Bundle optimization - optimize CSS and JS bundling to reduce edge requests
  experimental: {
    optimizePackageImports: ['lucide-react', '@vercel/analytics'],
    // Enable optimized CSS bundling
    optimizeCss: true,
  },
  // Advanced caching and compression
  compress: true,
  poweredByHeader: false,
  // Optimize production builds
  productionBrowserSourceMaps: false,
  // Minimize CSS and JS chunks
  swcMinify: true,
  async rewrites() {
    return [
      {
        source: '/api/proxy/:path*',
        destination: 'https://tsonglyricsapp.blogspot.com/:path*',
      },
      // Handle static pages with .html extension
      {
        source: '/privacy-policy-tamil-song-lyrics-app.html',
        destination: '/privacy-policy-tamil-song-lyrics-app',
      },
      {
        source: '/privacy',
        destination: '/privacy-policy-tamil-song-lyrics-app',
      },
      {
        source: '/about',
        destination: '/about-tamil-song-lyrics',
      },
      {
        source: '/terms',
        destination: '/disclaimer',
      },
      {
        source: '/tamil-song-lyrics-in-english.html',
        destination: '/tamil-song-lyrics-in-english',
      },
      // Handle .html URLs by rewriting to dynamic route (must come after static pages)
      {
        source: '/:slug.html',
        destination: '/:slug',
      },
    ];
  },
  async headers() {
    return [
      // Revalidate API - NO CACHE (must never be cached!)
      {
        source: '/api/revalidate',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0',
          },
          {
            key: 'CDN-Cache-Control',
            value: 'no-store',
          },
          {
            key: 'Vercel-CDN-Cache-Control',
            value: 'no-store',
          },
          {
            key: 'Pragma',
            value: 'no-cache',
          },
          {
            key: 'Expires',
            value: '0',
          },
        ],
      },
      // Security headers for all routes
      {
        source: '/(.*)',
        headers: [
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'origin-when-cross-origin',
          },
        ],
      },
      // CDN Cache headers for all pages (home, search, songs) but NOT API routes
      // Extended to 30 days to minimize CPU usage on Vercel free tier
      {
        source: '/:path((?!api|_next/static|_next/image|favicon.ico).*)*',
        headers: [
          {
            key: 'Cache-Control',
            value: 's-maxage=2592000, stale-while-revalidate=5184000',
          },
          {
            key: 'CDN-Cache-Control',
            value: 'max-age=2592000',
          },
          {
            key: 'Vercel-CDN-Cache-Control',
            value: 'max-age=2592000',
          },
          {
            key: 'Vary',
            value: 'Accept-Encoding',
          },
        ],
      },
      // Static assets caching
      {
        source: '/favicon.ico',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=2592000, s-maxage=2592000',
          },
        ],
      },
      {
        source: '/_next/static/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=31536000, immutable',
          },
        ],
      },
    ];
  },
  async redirects() {
    // console.log('🚫 Migration redirects disabled - using middleware for redirects');
    
    return [
      // Custom manual redirects (defined at top of file)
      ...customRedirects,
      
      // Legacy /song/ URLs redirect to root level  
      {
        source: '/song/:slug*',
        destination: '/:slug*',
        permanent: true,
      },
      
      // Date pattern redirects (moved from middleware)
      {
        source: '/:year(\\d{4})/:month(\\d{2})/:slug*',
        destination: '/:slug*',
        permanent: true,
      },
      
      // WordPress to Next.js migration redirects now handled by middleware
    ];
  },
};

module.exports = withBundleAnalyzer(nextConfig);
